;;; reader-epub-tests.el --- Epub regressions -*- lexical-binding: t; -*-

(require 'reader-test-helpers)

(ert-deftest english-reading-mode-epub-quote-prefetch-matches-playback ()
  (with-temp-buffer
    (insert "「知りたいからよ」\n\n「どうして知りたいの？」\n\n「なぜなの？　理由を話します」\n\n次の文章です。")
    (setq-local major-mode 'nov-mode)
    (let ((kokoro-reader-backend 'macos)
          (kokoro-reader-macos-voice "Kyoko (Enhanced)")
          (english-reading-mode-macos-continuous-sentence-count 2)
          (english-reading-mode--continuous-state
           (list :buffer (current-buffer))))
      (goto-char (point-min))
      (let* ((first (english-reading-mode--current-continuous-speech-spec))
             (end (plist-get first :end))
             (prefetched (car (english-reading-mode--speech-texts-after-position
                               (current-buffer) end 1))))
        (goto-char end)
        (skip-chars-forward " \t\n\r　 ")
        (let ((actual (plist-get (english-reading-mode--current-continuous-speech-spec)
                                 :text)))
          (should (equal (kokoro-reader--macos-key prefetched)
                         (kokoro-reader--macos-key actual))))))))

(ert-deftest english-reading-mode-epub-continuous-crosses-chapters-and-stops ()
  ;; Exercise the completion path with and without trailing whitespace: at
  ;; point-max, Emacs may return the last sentence instead of nil.
  (dolist (suffix '("" "\n\n" "　 \n"))
    (save-window-excursion
      (with-temp-buffer
        (switch-to-buffer (current-buffer))
        (setq-local major-mode 'nov-mode)
        (setq-local sentence-end-double-space nil)
        (setq-local nov-documents
                    (vector (concat "First sentence. Second sentence." suffix)
                            "" " \n\t" "次の章です。\n"))
        (setq-local nov-documents-index 0)
        (insert (aref nov-documents 0))
        (goto-char (point-min))
        (let ((english-reading-mode--continuous-state
               (list :buffer (current-buffer) :window (selected-window)
                     :frame (selected-frame)))
              (english-reading-mode--continuous-timer nil)
              (english-reading-mode--exact-player-finish-p t)
              spoken context)
          (cl-letf (((symbol-function 'nov-next-document)
                     (lambda ()
                       (cl-incf nov-documents-index)
                       (erase-buffer)
                       (insert (aref nov-documents nov-documents-index))
                       (goto-char (point-min))))
                    ((symbol-function 'kokoro-reader-macos-has-pending-p)
                     (lambda () nil))
                    ((symbol-function 'kokoro-reader--clear-macos-prefetch)
                     #'ignore)
                    ((symbol-function 'english-reading-mode-speak-current-sentence)
                     (lambda ()
                       (let ((bounds (english-reading-mode--sentence-bounds)))
                         (push (string-trim (buffer-substring-no-properties
                                             (car bounds) (cdr bounds))
                                            "[ \t\n\r　 ]+" "[ \t\n\r　 ]+") spoken)
                         (setq context (list :buffer (current-buffer)
                                             :end (cdr bounds)))))))
            (english-reading-mode-speak-current-sentence)
            (english-reading-mode--continuous-speech-finished context)
            (should (= nov-documents-index 0))
            (english-reading-mode--continuous-speech-finished context)
            (should (= nov-documents-index 3))
            (should english-reading-mode--continuous-state)
            (english-reading-mode--continuous-speech-finished context)
            (should-not english-reading-mode--continuous-state)
            (should (equal (reverse spoken)
                           '("First sentence." "Second sentence." "次の章です。")))))))))

(ert-deftest english-reading-mode-epub-japanese-dialogue-does-not-skip-chapter ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (setq-local major-mode 'nov-mode)
      (setq-local sentence-end-double-space nil)
      (setq-local kokoro-reader-backend 'macos)
      (setq-local nov-documents [first second])
      (setq-local nov-documents-index 0)
      (insert "最初の文です。\n\n「な、なに！？」\n\n「どうだったの！？」\n\nまだ同じ章の本文です。\n")
      (goto-char (point-min))
      (let ((english-reading-mode--continuous-state
             (list :buffer (current-buffer) :window (selected-window)
                   :frame (selected-frame)))
            (english-reading-mode-macos-continuous-sentence-count 2)
            (english-reading-mode--exact-player-finish-p t)
            spoken context)
        (cl-letf (((symbol-function 'nov-next-document)
                   (lambda () (ert-fail "Skipped into the next chapter")))
                  ((symbol-function 'kokoro-reader-macos-has-pending-p)
                   (lambda () nil))
                  ((symbol-function 'english-reading-mode-speak-current-sentence)
                   (lambda ()
                     (let ((spec (english-reading-mode--current-continuous-speech-spec)))
                       (push (plist-get spec :text) spoken)
                       (setq context spec)))))
          (english-reading-mode-speak-current-sentence)
          (let ((expected (english-reading-mode--next-speech-text context)))
            (english-reading-mode--continuous-speech-finished context)
            (should (equal (car spoken) expected)))
          (should (= nov-documents-index 0))
          (should (equal (reverse spoken)
                         '("最初の文です。 「な、なに！？」"
                           "「どうだったの！？」 まだ同じ章の本文です。"))))))))

(ert-deftest english-reading-mode-epub-fullwidth-space-makes-forward-progress ()
  (with-temp-buffer
    (setq-local major-mode 'nov-mode)
    (setq-local sentence-end-double-space nil)
    (insert "「最初の台詞よ！　どうだったの！？」\n\n次の文です。　 \n")
    (goto-char (point-min))
    (search-forward "！")
    (let* ((end (point))
           (bounds (english-reading-mode--sentence-bounds-at-point)))
      (should (> (car bounds) end))
      (should (> (cdr bounds) end))
      (should (equal (buffer-substring-no-properties (car bounds) (cdr bounds))
                     "どうだったの！？」")))
    (goto-char (point-max))
    (skip-chars-backward " \n　 ")
    (should-not (english-reading-mode--sentence-bounds-at-point))))

(ert-deftest english-reading-mode-epub-unrecognized-text-is-not-chapter-end ()
  (with-temp-buffer
    (setq-local major-mode 'nov-mode)
    (setq-local nov-documents [first second])
    (setq-local nov-documents-index 0)
    (insert "Unread text remains here.")
    (goto-char (point-min))
    (cl-letf (((symbol-function 'english-reading-mode--sentence-bounds-at-point)
               (lambda () nil))
              ((symbol-function 'nov-next-document)
               (lambda () (ert-fail "Advanced with unread text"))))
      (should-error (english-reading-mode--continuous-epub-next) :type 'user-error)
      (should (= nov-documents-index 0)))))

(ert-deftest english-reading-mode-epub-chapter-end-advances-without-completion ()
  (with-temp-buffer
    (setq-local major-mode 'nov-mode)
    (setq-local nov-documents [first second])
    (setq-local nov-documents-index 0)
    (insert "Last sentence.\n")
    (goto-char (point-max))
    (let (spoken)
      (cl-letf (((symbol-function 'nov-next-document)
                 (lambda ()
                   (setq nov-documents-index 1)
                   (erase-buffer)
                   (insert "Next chapter.")))
                ((symbol-function 'english-reading-mode-speak-current-sentence)
                 (lambda () (setq spoken (thing-at-point 'sentence t)))))
        (english-reading-mode--continuous-default-next)
        (should (equal spoken "Next chapter."))))))

(ert-deftest my-read-k-background-page-update-does-not-steal-epub-tab ()
  (my-read-k-test--isolated
   (save-window-excursion
     (let* ((frame (selected-frame))
            (window (selected-window))
            (kindle-buffer (generate-new-buffer " *my-read-k-hidden-tab*"))
            (epub-buffer (generate-new-buffer " *my-read-epub-visible-tab*"))
            (speech-count 0))
       (unwind-protect
           (progn
             (setq my-read-k--frame frame my-read-k--buffer kindle-buffer)
             (set-frame-parameter frame 'my-reading-kindle-window window)
             (set-window-buffer window epub-buffer)
             (cl-letf (((symbol-function 'my-read-k--refresh-followers) #'ignore)
                       ((symbol-function 'english-reading-mode-next-sentence)
                        (lambda () (cl-incf speech-count)))
                       ((symbol-function 'english-reading-mode--speak-at-point)
                        (lambda () (cl-incf speech-count))))
               (my-read-k--apply-page
                '((text . "Updated Kindle sentence.") (ocrMs . 1)) 'next t))
             (should (eq (window-buffer window) epub-buffer))
             (should (= speech-count 0))
             (with-current-buffer kindle-buffer
               (should (equal (buffer-string) "Updated Kindle sentence.\n"))))
         (set-frame-parameter frame 'my-reading-kindle-window nil)
         (kill-buffer kindle-buffer)
         (kill-buffer epub-buffer))))))

(provide 'reader-epub-tests)
