;;; reader-http-playback-tests.el --- Remote playback tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'reader-http-speech-transport)

(ert-deftest reader-http-playback-cancelled-request-never-restarts-prefetch ()
  (let* ((entry (list :id 1 :http-payload "{}" :http-cancelled nil :process nil))
         (kokoro-reader--macos-prefetch-queue (list entry))
         (kokoro-reader--kokoro-request-processes nil)
         sentinel launched)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args) (setq sentinel (plist-get args :sentinel)) 'test-process))
              ((symbol-function 'process-send-string) #'ignore)
              ((symbol-function 'process-send-eof) #'ignore)
              ((symbol-function 'process-status) (lambda (_) 'signal))
              ((symbol-function 'process-exit-status) (lambda (_) 9))
              ((symbol-function 'kokoro-reader--launch-pending-requests)
               (lambda () (setq launched t))))
      (reader-http-speech-transport--start-request #'ignore entry)
      (reader-http-speech-transport--mark-cancelled)
      (funcall sentinel 'test-process "killed")
      (should-not launched)
      (should-not kokoro-reader--kokoro-request-processes))))

(ert-deftest reader-http-playback-payload-has-capability-without-wav ()
  (let ((reader-http-playback--session "session")
        (reader-http-playback--delivery-token "token")
        (reader-http-speech-playback-target "desktop")
        (reader-http-speech-playback-endpoint "http://player:8768")
        (reader-http-speech-playback-delivery-endpoint nil))
    (let* ((entry (list :id 7 :queued t :http-payload "{\"text\":\"本文\",\"language\":\"ja\"}"))
           (request (json-read-from-string (reader-http-playback--request entry)))
           (playback (alist-get 'playback request)))
      (should (equal (alist-get 'text request) "本文"))
      (should (equal (alist-get 'target playback) "desktop"))
      (should (equal (alist-get 'endpoint playback) "http://player:8768"))
      (should (= (alist-get 'id playback) 7))
      (should (equal (alist-get 'delivery_token playback) "token")))))

(ert-deftest reader-http-playback-completion-comes-only-from-device ()
  (let* ((reader-http-speech-transport-mode t)
         (reader-http-speech-playback-endpoint "http://player")
         (entry (list :id 7 :announced t))
         (kokoro-reader--macos-prefetch-queue (list entry))
         (kokoro-reader--macos-current-entry nil)
         (kokoro-reader-player-finish-hook nil)
         (completed 0))
    (add-hook 'kokoro-reader-player-finish-hook (lambda () (cl-incf completed)))
    (kokoro-reader--handle-macos-bridge-event '(:event "loaded" :id 7))
    (should (= completed 0))
    (kokoro-reader--handle-macos-bridge-event '(:event "started" :id 7))
    (should (eq kokoro-reader--macos-current-entry entry))
    (should (= completed 0))
    (kokoro-reader--handle-macos-bridge-event '(:event "finished" :id 7))
    (should (= completed 1))
    (should-not kokoro-reader--macos-prefetch-queue)
    (kokoro-reader--handle-macos-bridge-event '(:event "finished" :id 7))
    (should (= completed 1))))

(ert-deftest reader-http-playback-errors-stop-without-advancing ()
  (let ((reader-http-speech-transport-mode t)
        (reader-http-speech-playback-endpoint "http://player") stopped advanced)
    (cl-letf (((symbol-function 'english-reading-mode-stop-continuous)
               (lambda () (setq stopped t))))
      (reader-http-playback--event (lambda (_) (setq advanced t))
                                   '(:event "error" :message "lost audio device")))
    (should stopped)
    (should-not advanced)))

(ert-deftest reader-http-playback-target-is-part-of-prefetch-key ()
  (let ((reader-http-speech-transport-mode t)
        (reader-http-speech-playback-endpoint nil))
    (let ((local (reader-http-speech-transport--key '("text"))))
      (setq reader-http-speech-playback-endpoint "http://player")
      (should-not (equal local (reader-http-speech-transport--key '("text")))))))

(ert-deftest reader-http-playback-generator-url-override ()
  (let ((reader-http-playback--session "session")
        (reader-http-playback--delivery-token "token")
        (reader-http-speech-playback-endpoint "http://control:8768")
        (reader-http-speech-playback-delivery-endpoint "http://forward:18768"))
    (let* ((entry '(:queued t :id 7 :http-payload "{\"text\":\"Hello\"}"))
           (request (json-read-from-string (reader-http-playback--request entry))))
      (should (equal (alist-get 'endpoint (alist-get 'playback request))
                     "http://forward:18768")))))

(ert-deftest reader-http-playback-settings-defined-on-load ()
  ;; Do not let-bind the option here: that would hide a missing definition.
  (should (boundp 'reader-http-speech-playback-delivery-endpoint))
  (let ((reader-http-speech-transport-mode t))
    (should (reader-http-speech-transport--key '("startup")))))
