;;; reader-document-tests.el --- Document and lifecycle boundaries -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'my-read-k2)

(ert-deftest reader-document-dispatches-built-in-backends ()
  (dolist (entry '((text-mode . text) (nov-mode . epub)
                   (eww-mode . eww) (pdf-view-mode . pdf)
                   (doc-view-mode . pdf) (my-read-k-document-mode . kindle)))
    (with-temp-buffer
      (setq major-mode (car entry))
      (when (eq (cdr entry) 'pdf)
        (setq-local buffer-file-name "/tmp/reader.pdf"))
      (should (eq (reader-document-backend) (cdr entry))))))

(ert-deftest reader-document-custom-backend-inherits-and-reloads ()
  (let ((reader-document--backends (copy-tree reader-document--backends)))
    (reader-document-register 'test (lambda () t)
                              '(:title (lambda (&optional _) "First")) 'text)
    (reader-document-register 'test (lambda () t)
                              '(:title (lambda (&optional _) "Second")) 'text)
    (with-temp-buffer
      (insert "A sentence.")
      (goto-char (point-min))
      (should (equal (reader-document-title) "Second"))
      (should (equal (car (reader-document-current-sentence)) "A sentence."))
      (should (= 1 (cl-count 'test reader-document--backends :key #'car))))))

(ert-deftest reader-document-detects-inheritance-cycles-and-missing-operations ()
  (let ((reader-document--backends nil))
    (reader-document-register 'a (lambda () t) nil 'b)
    (reader-document-register 'b (lambda () nil) nil 'a)
    (should-error (reader-document-call :missing))
    (reader-document-register 'a (lambda () t) nil)
    (should-error (reader-document-call :missing) :type 'user-error)))

(ert-deftest reader-document-text-navigation-and-end ()
  (with-temp-buffer
    (text-mode)
    (setq-local sentence-end-double-space nil)
    (insert "First sentence. Second sentence.")
    (goto-char (point-min))
    (should (equal (car (reader-document-current-sentence)) "First sentence."))
    (reader-document-next-sentence)
    (should (equal (car (reader-document-current-sentence)) "Second sentence."))
    (reader-document-previous-sentence)
    (should (= (point) (point-min)))
    (reader-document-previous-sentence)
    (should (= (point) (point-min)))
    (reader-document-next-sentence)
    (should-error (reader-document-call :continue) :type 'user-error)))

(ert-deftest reader-document-text-location-round-trip ()
  (save-window-excursion
    (with-temp-buffer
      (text-mode)
      (setq-local buffer-file-name "/tmp/document.txt")
      (insert "First line.\nSecond line.\nThird line.")
      (switch-to-buffer (current-buffer))
      (goto-char 14)
      (let ((record (reader-document-current-location (selected-window))))
        (goto-char 1)
        (reader-document-restore-location record (selected-window))
        (should (= (point) 14))
        (should (eq (plist-get record :type) 'text))))))

(ert-deftest reader-document-pdf-sentence-uses-hidden-text ()
  (with-temp-buffer
    (setq major-mode 'pdf-view-mode)
    (setq-local buffer-file-name "/tmp/reader.pdf")
    (let ((location (list "Extracted text" 'hidden 10 24)))
      (cl-letf (((symbol-function 'english-reading-mode--pdf-location)
                 (lambda () location)))
        (should (eq (reader-document-current-sentence) location))))))

(ert-deftest reader-document-epub-location-restores-spine ()
  (save-window-excursion
    (with-temp-buffer
      (setq major-mode 'nov-mode)
      (setq-local nov-documents [one two] nov-documents-index 1)
      (insert "A chapter.")
      (switch-to-buffer (current-buffer))
      (goto-char 4)
      (let ((record (reader-document-current-location (selected-window))) restored)
        (cl-letf (((symbol-function 'nov-goto-document)
                   (lambda (index) (setq restored index))))
          (goto-char 1)
          (reader-document-restore-location record (selected-window)))
        (should (eq (plist-get record :type) 'epub))
        (should (= restored 1))
        (should (= (point) 4))))))

(ert-deftest reader-document-eww-reused-buffer-invalidates-session ()
  (save-window-excursion
    (with-temp-buffer
      (setq major-mode 'eww-mode)
      (setq-local eww-data '(:url "https://example.test/one"))
      (switch-to-buffer (current-buffer))
      (let ((english-reading-mode--continuous-state
             (list :buffer (current-buffer) :window (selected-window)
                   :frame (selected-frame) :document (reader-document-identity))))
        (should (english-reading-mode--continuous-live-p))
        (setq eww-data '(:url "https://example.test/two"))
        (should-not (english-reading-mode--continuous-live-p))))))

(ert-deftest reader-document-switched-window-invalidates-session ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (let ((english-reading-mode--continuous-state
             (list :buffer (current-buffer) :window (selected-window)
                   :frame (selected-frame))))
        (should (english-reading-mode--continuous-live-p))
        (set-window-buffer (selected-window) (get-buffer-create "*scratch*"))
        (should-not (english-reading-mode--continuous-live-p))))))

(ert-deftest reader-document-stale-timer-cannot-advance-new-session ()
  (let ((english-reading-mode--continuous-generation 10)
        (english-reading-mode--continuous-state nil)
        (english-reading-mode--continuous-timer nil)
        (english-reading-mode--continuous-warmup-timer nil)
        (english-reading-mode--macos-prefetch-monitor-timer nil)
        callback (calls 0))
    (cl-letf (((symbol-function 'run-at-time)
               (lambda (_delay _repeat function) (setq callback function)))
              ((symbol-function 'kokoro-reader--clear-macos-prefetch) #'ignore))
      (english-reading-mode--session-timer 0 nil (lambda () (cl-incf calls)))
      (funcall callback)
      (should (= calls 1))
      (english-reading-mode-stop-continuous t)
      (setq english-reading-mode--continuous-state (list :buffer (current-buffer)))
      (funcall callback)
      (should (= calls 1)))))

(ert-deftest reader-document-kill-stops-only-its-own-speech ()
  (let ((buffer (generate-new-buffer " *reader-lifecycle*"))
        (english-reading-mode--continuous-state nil)
        (english-reading-mode--active-speech nil) calls)
    (unwind-protect
        (cl-letf (((symbol-function 'english-reading-mode-stop-continuous)
                   (lambda (&rest _) (push (current-buffer) calls))))
          (with-current-buffer buffer (text-mode) (english-reading-mode 1))
          (with-temp-buffer (text-mode) (english-reading-mode 1))
          (should-not calls)
          (setq english-reading-mode--continuous-state (list :buffer buffer))
          (kill-buffer buffer)
          (should (equal calls (list buffer))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest reader-document-stale-bridge-output-is-ignored ()
  (let ((kokoro-reader--macos-bridge-process 'new)
        (kokoro-reader--macos-bridge-fragment "tail")
        (my-read-k--process 'new)
        (my-read-k--process-output "tail") seen)
    (cl-letf (((symbol-function 'kokoro-reader--handle-macos-bridge-event)
               (lambda (_) (setq seen t)))
              ((symbol-function 'my-read-k--dispatch-response)
               (lambda (_) (setq seen t))))
      (kokoro-reader--macos-bridge-filter 'old "{\"event\":\"ready\"}\n")
      (my-read-k--process-filter 'old "{\"id\":1}\n"))
    (should-not seen)
    (should (equal kokoro-reader--macos-bridge-fragment "tail"))
    (should (equal my-read-k--process-output "tail"))))

(ert-deftest reader-document-translation-stop-invalidates-before-sentinel ()
  (let ((my/read-translate-process 'request) observed)
    (cl-letf (((symbol-function 'process-live-p) (lambda (_) t))
              ((symbol-function 'delete-process)
               (lambda (_) (setq observed my/read-translate-process))))
      (my/read-translate-stop-process))
    (should-not observed)
    (should-not my/read-translate-process)))

(ert-deftest reader-document-kindle-filter-survives-callback-reentry ()
  (let ((my-read-k--process 'current) (my-read-k--process-output "") seen)
    (cl-letf (((symbol-function 'my-read-k--dispatch-response)
               (lambda (response)
                 (let ((id (alist-get 'id response)))
                   (push id seen)
                   (when (= id 1)
                     (my-read-k--process-filter 'current "{\"id\":3}\n"))))))
      (my-read-k--process-filter 'current "{\"id\":1}\n{\"id\":2}\n"))
    (should (equal (nreverse seen) '(1 3 2)))
    (should (string-empty-p my-read-k--process-output))))

(ert-deftest reader-document-reconnect-during-filter-discards-old-batch ()
  (let ((my-read-k--process 'old) (my-read-k--process-output "")
        (kokoro-reader--macos-bridge-process 'old)
        (kokoro-reader--macos-bridge-fragment "") kindle-seen speech-seen)
    (cl-letf (((symbol-function 'my-read-k--dispatch-response)
               (lambda (response)
                 (push (alist-get 'id response) kindle-seen)
                 (setq my-read-k--process 'new my-read-k--process-output "new-tail")))
              ((symbol-function 'kokoro-reader--handle-macos-bridge-event)
               (lambda (event)
                 (push (plist-get event :id) speech-seen)
                 (setq kokoro-reader--macos-bridge-process 'new
                       kokoro-reader--macos-bridge-fragment "new-tail"))))
      (my-read-k--process-filter 'old "{\"id\":1}\n{\"id\":2}\n")
      (kokoro-reader--macos-bridge-filter 'old "{\"id\":1}\n{\"id\":2}\n"))
    (should (equal kindle-seen '(1)))
    (should (equal speech-seen '(1)))
    (should (equal my-read-k--process-output "new-tail"))
    (should (equal kokoro-reader--macos-bridge-fragment "new-tail"))))

(ert-deftest reader-document-translation-completion-rejects-reused-document ()
  (save-window-excursion
    (with-temp-buffer
      (setq major-mode 'eww-mode)
      (setq-local eww-data '(:url "https://example.test/old"))
      (switch-to-buffer (current-buffer))
      (let ((my/read-translate-process nil)
            (my/read-translate-last-target 'target)
            (my/read-google-translation-fallback t)
            sentinel response-buffer (requests 0) displayed)
        (unwind-protect
            (cl-letf (((symbol-function 'make-process)
                       (lambda (&rest options)
                         (cl-incf requests)
                         (setq sentinel (plist-get options :sentinel)
                               response-buffer (plist-get options :buffer))
                         'request))
                      ((symbol-function 'process-status) (lambda (_) 'exit))
                      ((symbol-function 'process-exit-status) (lambda (_) 1))
                      ((symbol-function 'process-buffer) (lambda (_) response-buffer))
                      ((symbol-function 'my/read-translate-display)
                       (lambda (&rest _) (setq displayed t))))
              (my/read--start-translation-request
               'local (selected-frame) (selected-window) 'target 'sentence
               "Old text" (current-buffer))
              (setq eww-data '(:url "https://example.test/new"))
              (funcall sentinel 'request "failed")
              (should (= requests 1))
              (should-not displayed)
              (should-not my/read-translate-process)
              (should-not (buffer-live-p response-buffer)))
          (when (buffer-live-p response-buffer) (kill-buffer response-buffer)))))))

(ert-deftest reader-document-reloading-fallback-preserves-specialized-dispatch ()
  (let* ((reader-document--backends (copy-tree reader-document--backends))
         (text (assq 'text reader-document--backends)))
    (reader-document-register 'text (nth 1 text) (nth 2 text))
    (with-temp-buffer
      (setq major-mode 'nov-mode)
      (should (eq (reader-document-backend) 'epub)))))

(ert-deftest reader-state-file-failed-rename-preserves-previous-data ()
  (let* ((directory (make-temp-file "reader-state-test-" t))
         (file (expand-file-name "state.el" directory)))
    (unwind-protect
        (progn
          (reader-state-file-write file '(original) ";;; state")
          (cl-letf (((symbol-function 'rename-file)
                     (lambda (&rest _) (signal 'file-error '("test rename failure")))))
            (should-error (reader-state-file-write file '(replacement) ";;; state")
                          :type 'file-error))
          (should (equal (reader-state-file-read file #'listp nil "state") '(original)))
          (should (equal (delete "." (delete ".." (directory-files directory)))
                         '("state.el"))))
      (delete-directory directory t))))

(provide 'reader-document-tests)
;;; reader-document-tests.el ends here
