;;; reader-ui-tests.el --- Ui regressions -*- lexical-binding: t; -*-

(require 'reader-test-helpers)

(ert-deftest my-read-dired-details-stay-private-after-revert ()
  (let* ((directory (make-temp-file "my-read-dired-" t))
         (file (expand-file-name "book.epub" directory))
         ordinary private)
    (unwind-protect
        (progn
          (write-region "book" nil file nil 'silent)
          (setq ordinary (dired-noselect directory))
          (with-current-buffer ordinary
            (dired-hide-details-mode -1)
            (dired-goto-file file))
          (setq private
                (my/read--private-dired-buffer ordinary (selected-frame)))
          (should-not (eq ordinary private))
          (with-current-buffer private
            (should dired-hide-details-mode)
            (should (equal (dired-get-filename) file))
            (revert-buffer)
            (should dired-hide-details-mode))
          (with-current-buffer ordinary
            (should-not dired-hide-details-mode)
            (should (eq (dired-noselect directory) ordinary)))
          (should (eq (my/read--private-dired-buffer ordinary (selected-frame))
                      private))
          (kill-buffer ordinary)
          (setq ordinary (dired-noselect directory))
          (should-not (eq ordinary private))
          (with-current-buffer ordinary
            (should-not dired-hide-details-mode)))
      (dolist (buffer (list ordinary private))
        (when (buffer-live-p buffer) (kill-buffer buffer)))
      (delete-directory directory t))))

(ert-deftest my-read-k-japanese-sentence-boundaries-work-one-at-a-time ()
  (with-temp-buffer
    (insert "これは最初の文です。これは二番目の文です！最後です？")
    (goto-char (point-min))
    (setq-local sentence-end-double-space nil)
    (should (equal (buffer-substring-no-properties
                    (car (bounds-of-thing-at-point 'sentence))
                    (cdr (bounds-of-thing-at-point 'sentence)))
                   "これは最初の文です。"))))

(ert-deftest english-reading-mode-j-speaks-current-and-n-moves-without-speaking ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (insert "First sentence. Second sentence. Third sentence.")
     (let ((my-read-k-mode t)
           spoken)
       (cl-letf (((symbol-function 'kokoro-reader--speak-bounds)
                  (lambda (beg end)
                    (push (buffer-substring-no-properties beg end) spoken))))
         (english-reading-mode 1)
         (goto-char (point-min))
         (english-reading-mode-speak-current-sentence)
         (should (equal (car spoken) "First sentence."))
         (should (= (point) (point-min)))
         (english-reading-mode-next-sentence)
         (should (= (length spoken) 1))
         (should (looking-at-p "Second sentence\\."))
         (english-reading-mode-previous-sentence)
         (should (= (length spoken) 1))
         (should (equal (car spoken) "First sentence."))
         (should (= (point) (point-min)))
         (english-reading-mode -1))))))

(ert-deftest english-reading-mode-k-moves-to-previous-sentence-without-speaking ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (insert "First sentence. Second sentence.")
     (let ((my-read-k-mode t)
           (spoken 0))
       (cl-letf (((symbol-function 'kokoro-reader--speak-bounds)
                  (lambda (&rest _) (cl-incf spoken))))
         (english-reading-mode 1)
         (goto-char (point-min))
         (search-forward "Second")
         (should (eq (lookup-key english-reading-mode-map (kbd "k"))
                     #'english-reading-mode-previous-sentence))
         (should (eq (key-binding (kbd "k")) #'my-read-k-backward))
         (call-interactively (key-binding (kbd "k")))
         (should (looking-at-p "First sentence\\."))
         (should (= spoken 0))
         (english-reading-mode -1))))))

(ert-deftest english-reading-mode-restores-buffer-sentence-spacing-setting ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (setq-local sentence-end-double-space t)
     (let ((my-read-k-mode t))
       (english-reading-mode 1)
       (should-not sentence-end-double-space)
       (english-reading-mode -1)
       (should sentence-end-double-space)
       (should (local-variable-p 'sentence-end-double-space))))))

(ert-deftest english-reading-mode-player-exit-finishes-without-polling ()
  (let* ((context '(:id 1 :text "Finished."))
         (english-reading-mode--active-speech context)
         (kokoro-reader--request-process nil)
         (kokoro-reader--player-process nil)
         finished)
    (cl-letf (((symbol-function 'english-reading-mode--finish)
               (lambda (actual) (setq finished actual))))
      (english-reading-mode--player-finished)
      (should (eq finished context)))))

(ert-deftest english-reading-mode-exact-player-exit-advances-synchronously ()
  (let* ((source-buffer (current-buffer))
         (context (list :buffer source-buffer :end 10))
         (english-reading-mode--continuous-state
          (list :buffer source-buffer))
         (english-reading-mode--continuous-timer nil)
         (english-reading-mode--exact-player-finish-p t)
         advanced)
    (cl-letf (((symbol-function 'english-reading-mode--continuous-next)
               (lambda () (setq advanced t)))
              ((symbol-function 'run-at-time)
               (lambda (&rest _)
                 (ert-fail "exact player exit must not schedule a timer"))))
      (english-reading-mode--continuous-speech-finished context)
      (should advanced)
      (should-not english-reading-mode--continuous-timer))))

(ert-deftest english-reading-mode-makes-buffer-read-only-and-restores-writable-state ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (should-not buffer-read-only)
     (english-reading-mode 1)
     (should buffer-read-only)
     (english-reading-mode -1)
     (should-not buffer-read-only))))

(ert-deftest english-reading-mode-preserves-an-existing-read-only-state ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (read-only-mode 1)
     (english-reading-mode 1)
     (should buffer-read-only)
     (english-reading-mode -1)
     (should buffer-read-only))))

(ert-deftest english-reading-mode-doc-view-highlights-and-restores-sentence ()
  (save-window-excursion
    (let ((pdf-buffer (generate-new-buffer " *pdf-view-highlight*"))
          (text-buffer (generate-new-buffer " *pdf-view-highlight-text*")))
      (unwind-protect
          (progn
            (switch-to-buffer pdf-buffer)
            (insert " ")
            (setq-local major-mode 'doc-view-mode)
            (setq-local buffer-file-name "/tmp/highlight.pdf")
            (setq-local english-reading-mode--pdf-text-buffer text-buffer)
            (let ((page-overlay (make-overlay (point-min) (point-max)))
                  (page-image '(image :type png :data "PNG bytes" :width 500)))
              (overlay-put page-overlay 'display page-image)
              (cl-letf (((symbol-function
                          'english-reading-mode--pdf-context-rectangles)
                         (lambda (_context)
                           '((:width 612.0 :height 792.0)
                             ((10.0 20.0 70.0 30.0)))))
                        ((symbol-function
                          'english-reading-mode--pdf-display-state)
                         (lambda (&optional _window)
                           (list page-overlay page-image nil)))
                        ((symbol-function
                          'english-reading-mode--pdf-svg-highlight)
                         (lambda (&rest _arguments) 'highlight-image)))
                (let ((context (list :window (selected-window)
                                     :buffer text-buffer
                                     :text "Spoken sentence."
                                     :beg 1 :end 17)))
                  (english-reading-mode--pdf-highlight-start context)
                  (should (eq (overlay-get page-overlay 'display)
                              'highlight-image))
                  ;; A real DocView state read now returns the installed SVG,
                  ;; not PAGE-IMAGE.  Restoration must use the captured value.
                  (cl-letf (((symbol-function
                              'english-reading-mode--pdf-display-state)
                             (lambda (&optional _window)
                               (list page-overlay 'highlight-image nil))))
                    (english-reading-mode--pdf-highlight-finish context))
                  (should (equal (overlay-get page-overlay 'display)
                                 page-image))))))
        (when (buffer-live-p pdf-buffer) (kill-buffer pdf-buffer))
        (when (buffer-live-p text-buffer) (kill-buffer text-buffer))))))

(ert-deftest my-read-k-keeps-current-reader-bindings ()
  (should (commandp 'my-read))
  (should (equal (help-function-arglist #'my/read--setup-frame t)
                 '(frame &optional kindle-buffer)))
  (should (eq (lookup-key english-reading-mode-map (kbd "j"))
              #'english-reading-mode-next-sentence))
  (should (eq (lookup-key english-reading-mode-map (kbd "k"))
              #'english-reading-mode-previous-sentence))
  (should (eq (lookup-key english-reading-mode-map (kbd "SPC"))
              #'english-reading-mode-speak-current-sentence))
  (with-temp-buffer
    (setq-local major-mode 'pdf-view-mode)
    (setq-local buffer-file-name "/tmp/reader-key-test.pdf")
    (should (eq (lookup-key english-reading-mode-map (kbd "C-v"))
                #'english-reading-mode-next-page))
    (should (eq (lookup-key english-reading-mode-map (kbd "M-v"))
                #'english-reading-mode-previous-page)))
  (should-not (lookup-key english-reading-mode-map (kbd "i")))
  (should (eq (lookup-key my-read-k-mode-map (kbd "k"))
              #'my-read-k-backward))
  (should (eq (lookup-key my-read-k-mode-map (kbd "SPC"))
              #'english-reading-mode-speak-current-sentence))
  (should-not (lookup-key my-read-k-mode-map (kbd "i")))
  (should (eq (lookup-key org-noter-doc-mode-map (kbd "i"))
              #'org-noter-insert-note))
  (should (eq (lookup-key my-read-k-mode-map (kbd "<down>"))
              #'my-read-k-down))
  (should (eq (lookup-key my-read-k-mode-map (kbd "<up>"))
              #'my-read-k-up))
  (should (eq (lookup-key my-read-k-mode-map (kbd "C-n"))
              #'my-read-k-down))
  (should (eq (lookup-key my-read-k-mode-map (kbd "C-p"))
              #'my-read-k-up))
  (should (eq (lookup-key my-read-k-mode-map (kbd "C-v"))
              #'my-read-k-next-page))
  (should (eq (lookup-key my-read-k-mode-map (kbd "M-v"))
              #'my-read-k-prev-page))
  (should (eq (lookup-key my-read-k-mode-map (kbd "r"))
              #'my-read-k-reconnect))
  (with-temp-buffer
    (my-read-k-mode 1)
    (english-reading-mode 1)
    (should (eq (key-binding (kbd "r")) #'my-read-k-reconnect))
    (english-reading-mode -1)
    (my-read-k-mode -1)))

(ert-deftest my-read-keys-only-apply-in-selected-center-window ()
  (save-window-excursion
    (let* ((frame (selected-frame))
           (center (selected-window))
           (other (split-window-right))
           (buffer (generate-new-buffer " *my-read-key-scope*")))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'my-reading-frame t)
            (set-frame-parameter frame 'my-reading-center-window center)
            (set-frame-parameter frame 'my-reading-center-windows (list center))
            (set-frame-parameter frame 'my-reading-epub-buffer buffer)
            (set-window-buffer center buffer)
            (with-current-buffer buffer
              (setq-local my/read-center-tab-frame frame)
              (setq-local english-reading-mode-key-active-predicate
                          #'my/read--center-window-active-p)
              (my-read-center-tab-mode 1)
              (english-reading-mode 1))
            (select-window center)
            (should (eq (key-binding (kbd "j"))
                        #'english-reading-mode-next-sentence))
            (should (eq (key-binding (kbd "k"))
                        #'english-reading-mode-previous-sentence))
            (should (eq (key-binding (kbd "SPC"))
                        #'english-reading-mode-speak-current-sentence))
            (should (eq (key-binding (kbd ";"))
                        #'my/read-next-word))
            (should (eq (key-binding (kbd "l"))
                        #'my/read-previous-word))
            (should (eq (key-binding (kbd "C-c p"))
                        #'kokoro-reader-speak-paragraph))
            ;; Even the same buffer must not carry my-read keys into a window
            ;; that is not the registered center reading pane.
            (set-window-buffer other buffer)
            (select-window other)
            (should-not (eq (key-binding (kbd "j"))
                            #'english-reading-mode-next-sentence))
            (should-not (eq (key-binding (kbd "k"))
                            #'english-reading-mode-previous-sentence))
            (should-not (eq (key-binding (kbd "SPC"))
                            #'english-reading-mode-speak-current-sentence))
            (should-not (eq (key-binding (kbd ";"))
                            #'my/read-next-word))
            (should-not (eq (key-binding (kbd "l"))
                            #'my/read-previous-word))
            (should-not (eq (key-binding (kbd "C-c p"))
                            #'kokoro-reader-speak-paragraph)))
        (set-frame-parameter frame 'my-reading-frame nil)
        (set-frame-parameter frame 'my-reading-center-window nil)
        (set-frame-parameter frame 'my-reading-center-windows nil)
        (set-frame-parameter frame 'my-reading-epub-buffer nil)
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest my-read-word-keys-move-between-word-beginnings ()
  (with-temp-buffer
    (insert "First, second third.")
    (goto-char (point-min))
    (my/read-next-word)
    (should (looking-at-p "second"))
    (my/read-next-word)
    (should (looking-at-p "third"))
    (my/read-previous-word)
    (should (looking-at-p "second"))
    (my/read-previous-word)
    (should (= (point) (point-min)))))

(ert-deftest my-read-org-buffer-is-not-registered-as-a-reading-tab ()
  (save-window-excursion
    (let* ((frame (selected-frame))
           (center (selected-window))
           (epub-buffer (generate-new-buffer " *my-read-real-epub*"))
           (org-buffer (generate-new-buffer " *my-read-org-input*")))
      (unwind-protect
          (progn
            (with-current-buffer org-buffer (org-mode))
            (set-frame-parameter frame 'my-reading-frame t)
            (set-frame-parameter frame 'my-reading-center-window center)
            (set-frame-parameter frame 'my-reading-center-windows (list center))
            (set-frame-parameter frame 'my-reading-epub-buffer epub-buffer)
            (set-window-buffer center org-buffer)
            (my/read--track-center-tab-buffer frame)
            (should (eq (frame-parameter frame 'my-reading-epub-buffer)
                        epub-buffer))
            (with-current-buffer org-buffer
              (should-not my-read-center-tab-mode)
              (should-not my/read-center-tab-frame)))
        (dolist (parameter '(my-reading-frame my-reading-center-window
                             my-reading-center-windows
                             my-reading-epub-buffer))
          (set-frame-parameter frame parameter nil))
        (kill-buffer epub-buffer)
        (kill-buffer org-buffer)))))

(ert-deftest my-read-registers-opened-files-in-source-specific-tabs ()
  (save-window-excursion
    (let* ((frame (selected-frame))
           (center (selected-window))
           (epub-buffer (generate-new-buffer " *my-read-opened-epub*"))
           (pdf-buffer (generate-new-buffer " *my-read-opened-pdf*"))
           (dired-buffer (generate-new-buffer " *my-read-opened-dired*")))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'my-reading-frame t)
            (set-frame-parameter frame 'my-reading-center-window center)
            (set-frame-parameter frame 'my-reading-center-windows (list center))
            (cl-letf (((symbol-function 'my/read--configure-center-tab-buffer)
                       #'ignore)
                      ((symbol-function 'my/read-org-noter-follow-source)
                       #'ignore))
              (dolist (entry `((,dired-buffer dired-mode
                                my-reading-dired-buffer)
                               (,epub-buffer nov-mode
                                my-reading-epub-buffer)
                               (,pdf-buffer pdf-view-mode
                                my-reading-pdf-buffer)))
                (with-current-buffer (nth 0 entry)
                  (setq major-mode (nth 1 entry))
                  (when (eq major-mode 'dired-mode)
                    (setq-local my/read-dired-owner-frame frame)))
                (set-window-buffer center (nth 0 entry))
                (my/read--track-center-tab-buffer frame)
                (should (eq (frame-parameter frame (nth 2 entry))
                            (nth 0 entry)))))
            (should (eq (frame-parameter frame 'my-reading-dired-buffer)
                        dired-buffer))
            (should (eq (frame-parameter frame 'my-reading-epub-buffer)
                        epub-buffer))
            (should (eq (frame-parameter frame 'my-reading-pdf-buffer)
                        pdf-buffer)))
        (dolist (parameter '(my-reading-frame my-reading-center-window
                             my-reading-center-windows my-reading-epub-buffer
                             my-reading-pdf-buffer my-reading-dired-buffer))
          (set-frame-parameter frame parameter nil))
        (dolist (buffer (list epub-buffer pdf-buffer dired-buffer))
          (kill-buffer buffer))))))

(ert-deftest my-read-followers-ignore-org-buffer-in-center-window ()
  (save-window-excursion
    (let* ((frame (selected-frame))
           (center (selected-window))
           (epub-buffer (generate-new-buffer " *my-read-follower-epub*"))
           (org-buffer (generate-new-buffer " *my-read-follower-org*"))
           (my-read-lookup-follow-mode t)
           (my-read-translate-follow-mode t)
           lookup-called
           translate-called)
      (unwind-protect
          (progn
            (set-frame-parameter frame 'my-reading-frame t)
            (set-frame-parameter frame 'my-reading-center-window center)
            (set-frame-parameter frame 'my-reading-center-windows (list center))
            (set-frame-parameter frame 'my-reading-epub-buffer epub-buffer)
            (with-current-buffer org-buffer (org-mode))
            (set-window-buffer center org-buffer)
            (select-window center)
            (cl-letf (((symbol-function 'my/read-word-at-window)
                       (lambda (_window) (setq lookup-called t) "word"))
                      ((symbol-function 'my/read-translate-update-for-frame)
                       (lambda (_frame _window)
                         (setq translate-called t))))
              (my/read-lookup-follow-post-command)
              (my/read-translate-follow-post-command))
            (should-not lookup-called)
            (should-not translate-called))
        (dolist (parameter '(my-reading-frame my-reading-center-window
                             my-reading-center-windows
                             my-reading-epub-buffer))
          (set-frame-parameter frame parameter nil))
        (kill-buffer epub-buffer)
        (kill-buffer org-buffer)))))

(ert-deftest my-read-unified-layout-has-left-reading-and-right-utility-panes ()
  (save-window-excursion
    (let* ((frame (selected-frame))
           (kindle-buffer (generate-new-buffer " *my-read-layout-kindle*"))
           (epub-buffer (generate-new-buffer " *my-read-layout-epub*"))
           (dired-buffer (generate-new-buffer " *my-read-layout-dired*"))
           (my/read-book-path "/virtual/book.epub")
           (lookup-frame-height
            (frame-parameter frame 'lookup-window-height))
           opened-paths)
      (unwind-protect
          (cl-letf (((symbol-function 'find-file)
                     (lambda (path)
                       (push path opened-paths)
                       (switch-to-buffer epub-buffer)
                       (setq major-mode 'nov-mode)))
                    ((symbol-function 'dired-noselect)
                     (lambda (_directory) dired-buffer))
                    ((symbol-function 'my/read--private-dired-buffer)
                     (lambda (source _frame) source))
                    ((symbol-function 'my-read-lookup-follow-mode) #'ignore)
                    ((symbol-function 'my-read-translate-follow-mode) #'ignore)
                    ((symbol-function 'my/read-lookup-follow-post-command) #'ignore)
                    ((symbol-function 'my/read-translate-follow-post-command) #'ignore)
                    ((symbol-function 'my/read-org-noter-follow-source) #'ignore))
            (set-frame-parameter frame 'my-reading-frame t)
            (my/read--setup-frame frame kindle-buffer)
            (let ((kindle-window (my/read-kindle-window frame))
                  (epub-window (my/read-epub-window frame))
                  (pdf-window (my/read-pdf-window frame))
                  (dired-window (my/read-dired-window frame))
                  (eww-window (my/read-eww-window frame))
                  (translate-window (my/read-translate-window frame))
                  (lookup-window (my/read-lookup-window frame))
                  (note-window (my/read-note-window frame))
                  (pdf-buffer (frame-parameter frame 'my-reading-pdf-buffer))
                  (eww-buffer (frame-parameter frame 'my-reading-eww-buffer)))
              (should (= (length (window-list frame)) 4))
              (should (window-live-p kindle-window))
              (should (window-live-p epub-window))
              (should (window-live-p pdf-window))
              (should (window-live-p dired-window))
              (should (window-live-p eww-window))
              (should (window-live-p translate-window))
              (should (window-live-p lookup-window))
              (should (window-live-p note-window))
              (should (eq kindle-window epub-window))
              (should (eq epub-window pdf-window))
              (should (eq pdf-window dired-window))
              (should (eq epub-window eww-window))
              (let ((reading-edges (window-edges kindle-window))
                    (note-edges (window-edges note-window))
                    (translate-edges (window-edges translate-window))
                    (lookup-edges (window-edges lookup-window)))
                (should (> (car note-edges) (car reading-edges)))
                (should (> (car translate-edges) (car reading-edges)))
                (should (= (car note-edges) (car translate-edges)))
                (should (= (car translate-edges) (car lookup-edges)))
                (should (= (cadr note-edges) (cadr reading-edges)))
                (should (> (cadr translate-edges) (cadr note-edges)))
                (should (> (cadr lookup-edges) (cadr translate-edges)))
                (should (= (nth 3 lookup-edges) (nth 3 reading-edges))))
              (should (eq (frame-parameter frame 'my-reading-note-window)
                          note-window))
              (with-current-buffer (window-buffer note-window)
                (should (derived-mode-p 'org-mode)))
              (should (= (frame-parameter frame 'lookup-window-height)
                         my/read-lookup-entry-window-height))
              (should (equal opened-paths
                             (list (expand-file-name my/read-book-path))))
              (should (= (length (my/read-center-windows frame)) 1))
              (should (eq (window-buffer dired-window) dired-buffer))
              (with-current-buffer kindle-buffer
                (should my-read-center-tab-mode)
                (should (equal (my/read-center-tab-buffers)
                               (list dired-buffer kindle-buffer pdf-buffer
                                     epub-buffer
                                     (frame-parameter frame 'my-reading-text-buffer)
                                     eww-buffer)))
                (should (equal (mapcar #'my/read-center-tab-name
                                       (my/read-center-tab-buffers))
                               '(" DIRED " " KINDLE " " PDF " " EPUB "
                                 " TEXT " " EWW ")))
                (with-current-buffer pdf-buffer
                  (should (eq my/read-center-tab-placeholder-type 'pdf))))
              (set-window-buffer kindle-window eww-buffer)
              (with-current-buffer eww-buffer
                (should (equal (plist-get eww-data :url) my/read-eww-url))
                (should (= line-spacing my/read-eww-line-spacing))
                (should (eq (cdr (assq 'math
                                       shr-external-rendering-functions))
                            #'my/read-eww-math-render))
                (should english-reading-mode)
                (should (eq (key-binding (kbd "j"))
                            #'english-reading-mode-next-sentence))
                (should (eq (key-binding (kbd "k"))
                            #'english-reading-mode-previous-sentence))
                (should (eq (key-binding (kbd "SPC"))
                            #'english-reading-mode-speak-current-sentence))
                (should-not (eq (key-binding (kbd "i"))
                                #'english-reading-mode-previous-sentence))
                (should (eq (key-binding (kbd "l"))
                            #'my/read-previous-word))
                (should (eq (key-binding (kbd ";"))
                            #'my/read-next-word)))
              (set-window-buffer dired-window dired-buffer)
              (my/read-toggle-center-tab)
              (should (eq (window-buffer kindle-window) kindle-buffer))
              (my/read-toggle-center-tab)
              (should (eq (window-buffer pdf-window) pdf-buffer))
              (my/read-toggle-center-tab)
              (should (eq (window-buffer epub-window) epub-buffer))
              (my/read-toggle-center-tab)
              (should (eq (window-buffer epub-window)
                          (frame-parameter frame 'my-reading-text-buffer)))
              (my/read-toggle-center-tab)
              (should (eq (window-buffer eww-window) eww-buffer))
              (should-not (my/read--center-automatic-lookup-p eww-window))
              (let ((my/read-eww-enable-automatic-lookup t))
                (should (my/read--center-automatic-lookup-p eww-window)))
              (my/read-toggle-center-tab)
              (should (eq (window-buffer dired-window) dired-buffer))))
        (dolist (buffer (list kindle-buffer epub-buffer dired-buffer
                              (frame-parameter frame 'my-reading-pdf-buffer)
                              (frame-parameter frame 'my-reading-eww-buffer)
                              (frame-parameter frame 'my-reading-translate-buffer)
                              (frame-parameter frame 'my-reading-lookup-ready-buffer)
                              (frame-parameter frame 'my-reading-note-ready-buffer)))
          (when (buffer-live-p buffer) (kill-buffer buffer)))
        (dolist (parameter '(my-reading-frame my-reading-center-window
                             my-reading-center-windows my-reading-kindle-window
                             my-reading-epub-window my-reading-pdf-window
                             my-reading-dired-window my-reading-eww-window
                             my-reading-kindle-buffer my-reading-epub-buffer
                             my-reading-pdf-buffer my-reading-dired-buffer
                             my-reading-kindle-placeholder-buffer
                             my-reading-pdf-placeholder-buffer
                             my-reading-epub-placeholder-buffer
                             my-reading-lookup-window my-reading-translate-window
                             my-reading-note-window my-reading-note-ready-buffer))
          (set-frame-parameter frame parameter nil))
        (set-frame-parameter frame 'my-reading-translate-buffer nil)
        (set-frame-parameter frame 'my-reading-lookup-ready-buffer nil)
        (set-frame-parameter frame 'my-reading-note-ready-buffer nil)
        (set-frame-parameter frame 'my-reading-eww-buffer nil)
        (set-frame-parameter frame 'lookup-window-height
                             lookup-frame-height)))))

;;; my-read-k-tests.el ends here

(ert-deftest my-read-text-files-register-and-speak-in-center-only ()
  (save-window-excursion
    (let* ((my/read-position-directory (make-temp-file "my-read-text-pos-" t))
           (frame (selected-frame))
           (saved-parameters (frame-parameters frame))
           (center (selected-window))
           (other (split-window-right)))
      (unwind-protect
          (progn
            (set-frame-parameter frame 'my-reading-frame t)
            (set-frame-parameter frame 'my-reading-center-window center)
            (set-frame-parameter frame 'my-reading-center-windows (list center))
            (dolist (entry '(("sample.md" text-mode "First sentence. Second sentence.")
                             ("sample.org" org-mode "最初の文です。次の文です。")
                             ("sample.txt" text-mode "First sentence. Second sentence.")))
              (with-temp-buffer
                (funcall (nth 1 entry))
                (setq-local buffer-file-name (expand-file-name (car entry)))
                (insert (nth 2 entry))
                (set-buffer-modified-p nil)
                (goto-char (point-min))
                (set-window-buffer center (current-buffer))
                (select-window center)
                (my/read--track-center-tab-buffer frame)
                (should english-reading-mode)
                (should buffer-read-only)
                (should (memq (current-buffer) (my/read-center-tab-buffers)))
                (should (equal " TEXT "
                               (my/read-center-tab-name (current-buffer))))
                (should (eq (key-binding (kbd "SPC"))
                            #'english-reading-mode-speak-current-sentence))
                (should (eq (key-binding (kbd "s"))
                            #'english-reading-mode-continuous-read))
                (let (spoken)
                  (cl-letf (((symbol-function 'kokoro-reader--speak-bounds)
                             (lambda (beg end)
                               (setq spoken (buffer-substring-no-properties beg end)))))
                    (call-interactively (key-binding (kbd "SPC"))))
                  (should (equal spoken (if (eq (nth 1 entry) 'org-mode)
                                            "最初の文です。" "First sentence."))))
                (when (eq (nth 1 entry) 'org-mode)
                  (should (equal my/read-source-language "ja"))
                  (should (eq kokoro-reader-backend 'macos)))
                (set-window-buffer other (current-buffer))
                (select-window other)
                (should-not (eq (key-binding (kbd "SPC"))
                                #'english-reading-mode-speak-current-sentence))
                (english-reading-mode -1)
                (should-not buffer-read-only))))
        (dolist (parameter '(my-reading-frame my-reading-center-window
                             my-reading-center-windows my-reading-text-buffer))
          (set-frame-parameter frame parameter
                               (cdr (assq parameter saved-parameters))))
        (delete-directory my/read-position-directory t)))))

(provide 'reader-ui-tests)
