;;; reader-http-settings-tests.el --- Reader settings reach HTTP -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
;; Translation networking is unrelated to these settings tests.
(unless (featurep 'google-translate-core) (provide 'google-translate-core))
(require 'my-read)
(require 'reader-http-speech-transport)

(ert-deftest reader-http-existing-language-and-speed-commands-update-request ()
  (with-temp-buffer
    (insert "Japanese and English test text.")
    (let ((kokoro-reader-backend 'kokoro)
          (kokoro-reader-voice "bf_emma")
          (kokoro-reader-lang-code "b")
          (kokoro-reader-speed 1.0)
          (my/read-japanese-speech-backend 'macos)
          (my/read-japanese-macos-voice "Kyoko (Enhanced)")
          (my/read-japanese-macos-rate 250)
          (reader-http-speech-transport-mode t)
          (buffer (current-buffer)) stopped)
      (cl-letf (((symbol-function 'my/read--center-window-active-p) (lambda () t))
                ((symbol-function 'my/read--text-file-buffer-p) (lambda (&rest _) t))
                ((symbol-function 'english-reading-mode-stop-continuous) (lambda (&rest _) (setq stopped t)))
                ((symbol-function 'my/read--stop-language-speech) (lambda (&rest _) nil))
                ((symbol-function 'buffer-list) (lambda (&rest _) (list buffer))))
        (my-read-set-speech-language 'ja)
        (should stopped)
        (let ((old-key (reader-http-speech-transport--key (kokoro-reader--macos-key "text"))))
          (my-read-change-japanese-speed 540)
          (let ((request (json-read-from-string (reader-http-speech-transport--payload "text"))))
            (should (equal (alist-get 'language request) "ja"))
            (should (= (alist-get 'rate request) 540))
            (should (equal (alist-get 'voice request) "Kyoko")))
          (should-not (equal old-key (reader-http-speech-transport--key (kokoro-reader--macos-key "text")))))
        (my-read-set-speech-language 'en)
        (my-read-change-english-speed 1.4)
        (let ((request (json-read-from-string (reader-http-speech-transport--payload "text"))))
          (should (equal (alist-get 'language request) "en"))
          (should (equal (alist-get 'backend request) "kokoro"))
          (should (= (alist-get 'speed request) 1.4)))
        ;; The independent HTTP command uses the same language profiles too.
        (let ((request (reader-http-speech--request "text" "ja")))
          (should (= (alist-get 'rate request) 540)))
        (let ((request (reader-http-speech--request "text" "en")))
          (should (= (alist-get 'speed request) 1.4)))))))
