;;; reader-speech-tests.el --- Speech regressions -*- lexical-binding: t; -*-

(require 'reader-test-helpers)

(ert-deftest my-read-japanese-epub-uses-macos-japanese-speech ()
  (with-temp-buffer
    (insert "あの日、わたしとあいつとの関係が壊れた。")
    (my/read--configure-speech-language)
    (should (equal my/read-source-language "ja"))
    (should (eq kokoro-reader-backend 'macos))
    (should (equal kokoro-reader-macos-voice
                   my/read-japanese-macos-voice))
    (should (= kokoro-reader-macos-rate 540))
    (should (= kokoro-reader-macos-rate
               (* 3 (default-value 'kokoro-reader-macos-rate))))))

(ert-deftest my-read-english-epub-clears-japanese-speech-overrides ()
  (with-temp-buffer
    (setq-local kokoro-reader-backend 'macos)
    (setq-local kokoro-reader-macos-voice "Kyoko (Enhanced)")
    (setq-local kokoro-reader-macos-rate 540)
    (insert "This is an English sentence.")
    (my/read--configure-speech-language)
    (should (equal my/read-source-language "en"))
    (should (eq kokoro-reader-backend 'kokoro))
    (should (equal kokoro-reader-macos-voice "Samantha"))
    (should-not (local-variable-p 'kokoro-reader-backend))
    (should-not (local-variable-p 'kokoro-reader-macos-voice))
    (should (= kokoro-reader-macos-rate my/read-english-macos-rate))))

(ert-deftest my-read-language-speeds-are-independent-and-survive-switching ()
  (let ((kokoro-reader-backend 'macos)
        (my/read-japanese-macos-rate 540)
        (my/read-english-macos-rate 180)
        (english-reading-mode--continuous-state nil)
        (kokoro-reader--overlay nil)
        (ja (generate-new-buffer " *speed-ja*"))
        (en (generate-new-buffer " *speed-en*"))
        (stops 0))
    (unwind-protect
        (cl-letf (((symbol-function 'english-reading-mode-stop-continuous)
                   (lambda (&optional _quiet) (cl-incf stops))))
          (with-current-buffer ja (my/read--configure-speech-language "ja"))
          (with-current-buffer en (my/read--configure-speech-language "en"))
          ;; Warmup may be active before any speech overlay exists.
          (setq english-reading-mode--continuous-state (list :buffer ja))
          (my-read-change-english-speed 240)
          (should (= stops 0))
          (should (= my/read-japanese-macos-rate 540))
          (should (= (buffer-local-value 'kokoro-reader-macos-rate ja) 540))
          (should (= (buffer-local-value 'kokoro-reader-macos-rate en) 240))
          (my-read-change-japanese-speed 420)
          (should (= stops 1))
          (should (= my/read-english-macos-rate 240))
          (should (= (buffer-local-value 'kokoro-reader-macos-rate ja) 420))
          (setq english-reading-mode--continuous-state (list :buffer en))
          (my-read-change-english-speed 260)
          (should (= stops 2))
          (with-current-buffer en
            (my/read--configure-speech-language "ja")
            (should (= kokoro-reader-macos-rate 420))
            (my/read--configure-speech-language "en")
            (should (= kokoro-reader-macos-rate 260))))
      (kill-buffer ja)
      (kill-buffer en))))

(ert-deftest my-read-language-speeds-reject-invalid-input-before-changing-state ()
  (let ((kokoro-reader-backend 'macos)
        (my/read-japanese-macos-rate 540)
        (my/read-english-macos-rate 180))
    (dolist (command '(my-read-change-japanese-speed my-read-change-english-speed))
      (dolist (rate '(0 -1 1.5 "200" nil))
        (should-error (funcall command rate) :type 'user-error)))
    (should (= my/read-japanese-macos-rate 540))
    (should (= my/read-english-macos-rate 180))))

(ert-deftest my-read-english-kokoro-speed-preserves-japanese-speed ()
  (let ((kokoro-reader-backend 'kokoro)
        (kokoro-reader-speed 1.0)
        (my/read-japanese-macos-rate 250)
        (english-reading-mode--continuous-state nil)
        (kokoro-reader--overlay nil))
    (with-temp-buffer
      (my/read--configure-speech-language "en")
      (my-read-change-english-speed 1.25)
      (should (= kokoro-reader-speed 1.25))
      (should (= (default-value 'kokoro-reader-speed) 1.25))
      (should (= my/read-japanese-macos-rate 250))
      (dolist (rate '(0 0.4 2.1 180 "1.0"))
        (should-error (my-read-change-english-speed rate) :type 'user-error))
      (should (= kokoro-reader-speed 1.25)))))

(ert-deftest my-read-english-backend-selection-preserves-japanese ()
  (let ((kokoro-reader-backend 'kokoro)
        (my/read-japanese-speech-backend 'irodori)
        (english-reading-mode--continuous-state nil)
        (kokoro-reader--overlay nil))
    (with-temp-buffer
      (my/read--configure-speech-language "ja")
      (let ((japanese-buffer (current-buffer)))
        (with-temp-buffer
          (setq-local my/read-speech-language-override 'en)
          (my/read--configure-speech-language)
          (cl-letf (((symbol-function 'completing-read)
                     (lambda (_prompt candidates &rest _args)
                       (should (equal candidates '("kokoro" "macos")))
                       "macos")))
            (call-interactively #'my-read-set-english-speech-backend))
          (should (eq kokoro-reader-backend 'macos))
          (my/read--configure-speech-language)
          (should (eq kokoro-reader-backend 'macos))
          (with-temp-buffer
            (my/read--configure-speech-language "en")
            (should (eq kokoro-reader-backend 'macos)))
          (with-current-buffer japanese-buffer
            (should (eq kokoro-reader-backend 'irodori))
            (should (equal kokoro-reader-model "irodori-tts")))
          (my-read-set-english-speech-backend 'kokoro)
          (should (eq kokoro-reader-backend 'kokoro))
          (should-error (my-read-set-english-speech-backend 'irodori)
                        :type 'user-error)
          (should (eq kokoro-reader-backend 'kokoro)))))))

(ert-deftest my-read-japanese-kokoro-switching-keeps-english-settings ()
  (let ((my/read-japanese-speech-backend 'macos)
        (my/read-japanese-kokoro-voice "jf_alpha")
        (my/read-japanese-kokoro-speed 1.0)
        (my/read-japanese-macos-rate 250)
        (kokoro-reader-backend 'kokoro)
        (kokoro-reader-voice "bf_emma")
        (kokoro-reader-lang-code "b")
        (kokoro-reader-speed 1.2)
        (english-reading-mode--continuous-state nil)
        (kokoro-reader--overlay nil))
    (with-temp-buffer
      (my/read--configure-speech-language "ja")
      (my-read-set-japanese-speech-backend 'kokoro)
      (should (eq kokoro-reader-backend 'kokoro))
      (should (equal kokoro-reader-voice "jf_alpha"))
      (should (equal kokoro-reader-lang-code "j"))
      (my-read-change-japanese-speed 1.1)
      (should (= kokoro-reader-speed 1.1))
      (should (= my/read-japanese-kokoro-speed 1.1))
      (should (= (default-value 'kokoro-reader-speed) 1.2))
      (should (= my/read-japanese-macos-rate 250))
      (my-read-change-english-speed 1.4)
      (should (= kokoro-reader-speed 1.1))
      (should (= (default-value 'kokoro-reader-speed) 1.4))
      (should-error (my-read-change-japanese-speed 250) :type 'user-error)
      (my/read--configure-speech-language "en")
      (should (equal kokoro-reader-voice "bf_emma"))
      (should (equal kokoro-reader-lang-code "b"))
      (should (= kokoro-reader-speed 1.4))
      (my/read--configure-speech-language "ja")
      (should (= kokoro-reader-speed 1.1))
      (my-read-set-japanese-speech-backend 'macos)
      (should (eq kokoro-reader-backend 'macos))
      (should (= kokoro-reader-macos-rate 250))
      (should-error (my-read-set-japanese-speech-backend 'invalid)
                    :type 'user-error))))

(ert-deftest my-read-irodori-filters-quotes-before-sending-and-prefetching ()
  (let ((kokoro-reader-backend 'irodori)
        (kokoro-reader--macos-prefetch-queue nil)
        (kokoro-reader--macos-current-entry nil)
        (kokoro-reader-kokoro-prefetch-count 2)
        queued)
    (should (equal (gethash "input" (json-parse-string
                                    (kokoro-reader--payload "「本文です。」」")))
                   "「本文です。"))
    (should (equal (kokoro-reader--kokoro-key "本文です。」")
                   (kokoro-reader--kokoro-key "本文です。")))
    (cl-letf (((symbol-function 'kokoro-reader--enqueue-kokoro-text)
               (lambda (text &optional _) (push text queued))))
      (kokoro-reader-prefetch-kokoro-texts '("」" "本文です。」" "次です。」")))
    (should (equal (nreverse queued) '("本文です。" "次です。")))
    (dolist (backend '(kokoro macos))
      (let ((kokoro-reader-backend backend))
        (should (equal (kokoro-reader--speech-text "本文です。」") "本文です。」"))))))

(ert-deftest my-read-irodori-empty-quote-advances-without-audio-or-wait ()
  (with-temp-buffer
    (insert "」")
    (let ((kokoro-reader-backend 'irodori)
          (kokoro-reader--macos-current-entry nil)
          (english-reading-mode t)
          (english-reading-mode--active-speech nil)
          (english-reading-mode--speech-watch-timer nil)
          (english-reading-mode--continuous-timer nil)
          (english-reading-mode--continuous-state (list :buffer (current-buffer)))
          (english-reading-mode-speech-finish-hook
           '(english-reading-mode--continuous-speech-finished))
          scheduled)
      (cl-letf (((symbol-function 'kokoro-reader--enqueue-kokoro-text)
                 (lambda (&rest _) (ert-fail "Empty text was sent")))
                ((symbol-function 'kokoro-reader-stop)
                 (lambda (&rest _) (ert-fail "Prefetch was cancelled")))
                ((symbol-function 'english-reading-mode--start-watch)
                 (lambda (&rest _) (ert-fail "Waiting for nonexistent audio")))
                ((symbol-function 'kokoro-reader-macos-has-pending-p)
                 (lambda () t))
                ((symbol-function 'run-at-time)
                 (lambda (delay _repeat callback &rest _)
                   (setq scheduled (list delay callback)))))
        (kokoro-reader--speak-bounds (point-min) (point-max)))
      (should (zerop (car scheduled)))
      (let (advanced)
        (cl-letf (((symbol-function 'english-reading-mode--continuous-next)
                   (lambda () (setq advanced t))))
          (funcall (cadr scheduled)))
        (should advanced))
      (should (= (plist-get english-reading-mode--continuous-state
                            :next-speech-position) (point-max)))
      (should-not english-reading-mode--active-speech)
      (should (equal (buffer-string) "」")))))

(ert-deftest my-read-kyoko-filters-bridge-input-and-prefetch-keys ()
  (let ((kokoro-reader-backend 'macos)
        (kokoro-reader-macos-voice "Kyoko (Enhanced)")
        (kokoro-reader-macos-prefetch-enabled t)
        (kokoro-reader-macos-prefetch-count 2)
        (kokoro-reader--macos-prefetch-queue nil)
        (kokoro-reader--macos-current-entry nil)
        (kokoro-reader--macos-next-id 0)
        sent)
    (cl-letf (((symbol-function 'kokoro-reader--ensure-macos-bridge)
               (lambda () 'bridge))
              ((symbol-function 'process-send-string)
               (lambda (_process text)
                 (push (gethash "text" (json-parse-string text)) sent))))
      (kokoro-reader-prefetch-macos-texts '("」）" "「本文です。）」」" "次です。）」"))
      (should (equal (reverse sent) '("本文です。" "次です。")))
      (should (kokoro-reader-macos-prefetch-ready-p "「本文です。）」」"))
      (kokoro-reader-prefetch-macos-texts '("「本文です。）」」" "次です。）」"))
      (should (= (length sent) 2)))
    (should (equal (kokoro-reader--speech-text "」\n\n「知りたいからよ」")
                   "知りたいからよ"))
    (should (equal (kokoro-reader--macos-key "」\n\n「知りたいからよ」")
                   (kokoro-reader--macos-key "知りたいからよ")))
    (should (equal (kokoro-reader--speech-text "　」\n\n「　") ""))
    (dolist (voice '("Kyoko" "Kyoko (Enhanced)"))
      (let ((kokoro-reader-macos-voice voice))
        (should (equal (kokoro-reader--speech-text "本文です。）」") "本文です。"))))
    (let ((kokoro-reader-macos-voice "Samantha"))
      (should (equal (kokoro-reader--speech-text "本文です。）」") "本文です。）」")))))

(ert-deftest my-read-kyoko-empty-quote-advances-without-audio-or-wait ()
  (with-temp-buffer
    (insert "」）")
    (let ((kokoro-reader-backend 'macos)
          (kokoro-reader-macos-voice "Kyoko (Enhanced)")
          (kokoro-reader--macos-current-entry nil)
          (english-reading-mode t)
          (english-reading-mode--active-speech nil)
          (english-reading-mode--speech-watch-timer nil)
          (english-reading-mode--continuous-timer nil)
          (english-reading-mode--continuous-state (list :buffer (current-buffer)))
          (english-reading-mode-speech-finish-hook
           '(english-reading-mode--continuous-speech-finished))
          scheduled)
      (cl-letf (((symbol-function 'kokoro-reader--enqueue-macos-text)
                 (lambda (&rest _) (ert-fail "Empty text was sent")))
                ((symbol-function 'kokoro-reader-stop)
                 (lambda (&rest _) (ert-fail "Prefetch was cancelled")))
                ((symbol-function 'english-reading-mode--start-watch)
                 (lambda (&rest _) (ert-fail "Waiting for nonexistent audio")))
                ((symbol-function 'kokoro-reader-macos-has-pending-p)
                 (lambda () t))
                ((symbol-function 'run-at-time)
                 (lambda (delay _repeat callback &rest _)
                   (setq scheduled (list delay callback)))))
        (kokoro-reader--speak-bounds (point-min) (point-max)))
      (should (zerop (car scheduled)))
      (let (advanced)
        (cl-letf (((symbol-function 'english-reading-mode--continuous-next)
                   (lambda () (setq advanced t))))
          (funcall (cadr scheduled)))
        (should advanced))
      (should (= (plist-get english-reading-mode--continuous-state
                            :next-speech-position) (point-max)))
      (should-not english-reading-mode--active-speech)
      (should (equal (buffer-string) "」）")))))

(ert-deftest my-read-kindle-quote-only-prefetch-is-not-synthesized ()
  (let ((kokoro-reader-backend 'kokoro)
        (kokoro-reader-kokoro-prefetch-count 6)
        (kokoro-reader--macos-prefetch-queue nil)
        (kokoro-reader--macos-current-entry nil)
        sent)
    (cl-letf (((symbol-function 'kokoro-reader--enqueue-kokoro-text)
               (lambda (text &rest _) (push text sent))))
      (kokoro-reader-prefetch-kokoro-texts '("あたしはあんまりわかんない。" "』" "次です。")))
    (should (equal (nreverse sent) '("あたしはあんまりわかんない。" "次です。")))
    (dolist (backend '(kokoro macos irodori))
      (let ((kokoro-reader-backend backend))
        (should (equal (kokoro-reader--speech-text "　』\n『……』") ""))))
    (should (equal (kokoro-reader--speech-text "『スープもあっさりしすぎてるし』")
                   "『スープもあっさりしすぎてるし』"))))

(ert-deftest my-read-kindle-quote-only-kokoro-advances-without-audio-or-wait ()
  (with-temp-buffer
    (insert "』")
    (let ((kokoro-reader-backend 'kokoro)
          (kokoro-reader-macos-voice "Kyoko (Enhanced)")
          (kokoro-reader--macos-current-entry nil)
          (english-reading-mode t)
          (english-reading-mode--active-speech nil)
          (english-reading-mode--speech-watch-timer nil)
          (english-reading-mode--continuous-timer nil)
          (english-reading-mode--continuous-state (list :buffer (current-buffer)))
          (english-reading-mode-speech-finish-hook
           '(english-reading-mode--continuous-speech-finished))
          scheduled)
      (cl-letf (((symbol-function 'kokoro-reader--enqueue-kokoro-text)
                 (lambda (&rest _) (ert-fail "Empty text was sent")))
                ((symbol-function 'kokoro-reader-stop)
                 (lambda (&rest _) (ert-fail "Prefetch was cancelled")))
                ((symbol-function 'english-reading-mode--start-watch)
                 (lambda (&rest _) (ert-fail "Waiting for nonexistent audio")))
                ((symbol-function 'kokoro-reader-macos-has-pending-p)
                 (lambda () t))
                ((symbol-function 'run-at-time)
                 (lambda (delay _repeat callback &rest _)
                   (setq scheduled (list delay callback)))))
        (kokoro-reader--speak-bounds (point-min) (point-max)))
      (should (zerop (car scheduled)))
      (let (advanced)
        (cl-letf (((symbol-function 'english-reading-mode--continuous-next)
                   (lambda () (setq advanced t))))
          (funcall (cadr scheduled)))
        (should advanced))
      (should (= (plist-get english-reading-mode--continuous-state
                            :next-speech-position) (point-max)))
      (should-not english-reading-mode--active-speech)
      (should (equal (buffer-string) "』")))))

(ert-deftest my-read-irodori-reference-profile-and-speed-stay-japanese ()
  (let ((my/read-japanese-speech-backend 'macos)
        (my/read-japanese-irodori-speed 1.0)
        (my/read-japanese-kokoro-speed 1.1)
        (kokoro-reader-backend 'kokoro)
        (kokoro-reader-model "mlx-community/Kokoro-82M-bf16")
        (kokoro-reader-voice "bf_emma")
        (kokoro-reader-speed 1.2)
        (english-reading-mode--continuous-state nil)
        (kokoro-reader--overlay nil))
    (with-temp-buffer
      (my/read--configure-speech-language "ja")
      (my-read-set-japanese-speech-backend 'irodori)
      (should (eq kokoro-reader-backend 'irodori))
      (let ((payload (json-parse-string (kokoro-reader--payload "日本語です。"))))
        (should (equal (gethash "model" payload) "irodori-tts"))
        (should (equal (gethash "voice" payload) "asuka")))
      (my-read-change-japanese-speed 1.3)
      (should (= kokoro-reader-speed 1.3))
      (should (= my/read-japanese-irodori-speed 1.3))
      (should (= my/read-japanese-kokoro-speed 1.1))
      (should (= (default-value 'kokoro-reader-speed) 1.2))
      (my/read--configure-speech-language "en")
      (should (equal kokoro-reader-model "mlx-community/Kokoro-82M-bf16"))
      (should (equal kokoro-reader-voice "bf_emma"))
      (should (= kokoro-reader-speed 1.2))
      (my/read--configure-speech-language "ja")
      (my-read-set-japanese-speech-backend 'kokoro)
      (should-not (equal kokoro-reader-model "irodori-tts"))
      (should (= kokoro-reader-speed 1.1))
      (my-read-set-japanese-speech-backend 'macos)
      (should (eq kokoro-reader-backend 'macos)))))

(ert-deftest my-read-k-uses-reported-language-and-defaults-to-english ()
  (should (equal (my-read-k--language-from-result '((language . "en-US")))
                 "en"))
  (should (equal (my-read-k--language-from-result '((text . "English.")))
                 "en")))

(ert-deftest my-read-k-continuous-page-error-disarms-continuation ()
  (my-read-k-test--isolated
   (let ((stopped nil))
     (setq my-read-k--generation 2 my-read-k--busy-p t my-read-k--state 'busy)
     (cl-letf (((symbol-function 'english-reading-mode-stop-continuous)
                (lambda (&optional quiet) (setq stopped quiet))))
       (my-read-k--finish-page-request
        '((ok . nil) (error . ((code . "NO_TEXT") (message . "No text"))))
        2 'next 'continuous))
     (should stopped)
     (should-not my-read-k--busy-p)
     (should (eq my-read-k--state 'error)))))

(ert-deftest english-reading-mode-s-binds-continuous-sentence-reading ()
  (should (eq (lookup-key english-reading-mode-map (kbd "s"))
              #'english-reading-mode-continuous-read)))

(ert-deftest english-reading-mode-continuous-default-speaks-next-sentence ()
  (with-temp-buffer
    (insert "First sentence. Second sentence.")
    (goto-char (point-min))
    (setq-local sentence-end-double-space nil)
    (let (spoken)
      (cl-letf (((symbol-function 'english-reading-mode-speak-current-sentence)
                 (lambda () (setq spoken (thing-at-point 'sentence t)))))
        (english-reading-mode--continuous-default-next)
        (should (string-prefix-p "Second sentence." spoken))))))

(ert-deftest english-reading-mode-kokoro-continuous-speech-keeps-zero-gap ()
  (with-temp-buffer
    (let ((source-buffer (current-buffer))
          (english-reading-mode--continuous-state nil)
          (english-reading-mode--continuous-timer nil)
          scheduled-delay)
      (setq-local kokoro-reader-backend 'kokoro)
      (setq english-reading-mode--continuous-state
            (list :buffer source-buffer
                  :window (selected-window)
                  :frame (selected-frame)))
      (cl-letf (((symbol-function 'run-at-time)
                 (lambda (seconds _repeat _function &rest _args)
                   (setq scheduled-delay seconds)
                   'fake-timer)))
        (english-reading-mode--continuous-speech-finished
         (list :buffer source-buffer)))
      (should (zerop scheduled-delay)))))

(ert-deftest kokoro-reader-player-finish-hook-runs-from-current-sentinel ()
  (let ((kokoro-reader--player-process nil)
        (kokoro-reader--audio-file "/tmp/fake-speech.aiff")
        (kokoro-reader-player-finish-hook nil)
        sentinel
        finished)
    (add-hook 'kokoro-reader-player-finish-hook
              (lambda () (setq finished t)))
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest arguments)
                 (setq sentinel (plist-get arguments :sentinel))
                 'fake-player))
              ((symbol-function 'process-status) (lambda (_process) 'exit))
              ((symbol-function 'kokoro-reader--delete-audio-file) #'ignore))
      (kokoro-reader--play "/tmp/fake-speech.aiff" nil "macOS speech")
      (funcall sentinel 'fake-player "finished\n")
      (should finished)
      (should-not kokoro-reader--player-process))))

(ert-deftest english-reading-mode-prefetches-two-macos-chunks ()
  (with-temp-buffer
    (insert "一番です。二番です。三番です。四番です。五番です。六番です。")
    (setq-local sentence-end-double-space nil)
    (setq-local kokoro-reader-backend 'macos)
    (let ((source-buffer (current-buffer))
          (english-reading-mode--continuous-state nil)
          (english-reading-mode-macos-continuous-sentence-count 2)
          (english-reading-mode-macos-prefetch-chunk-count 3)
          queue-limit
          prefetched)
      (setq english-reading-mode--continuous-state
            (list :buffer source-buffer
                  :window (selected-window)
                  :frame (selected-frame)))
      (cl-letf (((symbol-function 'kokoro-reader-prefetch-macos-texts)
                 (lambda (texts)
                   (setq prefetched texts
                         queue-limit kokoro-reader-macos-prefetch-count))))
        (english-reading-mode--prefetch-next-macos-sentence
         (list :buffer source-buffer
               :beg (point-min)
               :end (save-excursion
                      (goto-char (point-min))
                      (forward-sentence 2)
                      (point))))
        (should (equal prefetched
                       '("三番です。四番です。"
                         "五番です。六番です。")))
        (should (= queue-limit 3))))))

(ert-deftest english-reading-mode-macos-prefetch-monitor-refills-periodically ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (setq-local kokoro-reader-backend 'macos)
      (let* ((source-buffer (current-buffer))
             (context (list :buffer source-buffer :beg 1 :end 1))
             (english-reading-mode--continuous-state
              (list :buffer source-buffer
                    :window (selected-window)
                    :frame (selected-frame)))
             (english-reading-mode--active-speech context)
             (english-reading-mode--macos-prefetch-monitor-timer nil)
             scheduled-delay scheduled-repeat scheduled-function refreshed)
        (cl-letf (((symbol-function 'run-with-timer)
                   (lambda (delay repeat function &rest _args)
                     (setq scheduled-delay delay
                           scheduled-repeat repeat
                           scheduled-function function)
                     'prefetch-monitor))
                  ((symbol-function
                    'english-reading-mode--prefetch-next-macos-sentence)
                   (lambda (active-context)
                     (setq refreshed active-context))))
          (english-reading-mode--start-macos-prefetch-monitor)
          (should (= scheduled-delay 0.5))
          (should (= scheduled-repeat 0.5))
          (funcall scheduled-function)
          (should (eq refreshed context)))))))

(ert-deftest english-reading-mode-continuous-waits-for-full-macos-warmup ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "一番です。二番です。三番です。")
      (setq-local sentence-end-double-space nil)
      (setq-local kokoro-reader-backend 'macos)
      (let* ((source-buffer (current-buffer))
             (window (selected-window))
             (frame (selected-frame))
             (spec (list :buffer source-buffer :beg 1 :end 6
                         :text "一番です。"))
             (english-reading-mode--continuous-state
              (list :buffer source-buffer :window window :frame frame
                    :warmup-spec spec
                    :warmup-texts '("一番です。" "二番です。")))
             (english-reading-mode--continuous-warmup-timer nil)
             (ready nil)
             scheduled spoken monitor-started)
        (cl-letf (((symbol-function 'kokoro-reader-prefetch-macos-texts)
                   #'ignore)
                  ((symbol-function 'kokoro-reader-macos-prefetch-ready-p)
                   (lambda (_text) ready))
                  ((symbol-function 'run-at-time)
                   (lambda (delay _repeat function &rest _args)
                     (setq scheduled (list delay function))
                     'warmup-timer))
                  ((symbol-function 'kokoro-reader--speak-bounds)
                   (lambda (beg end) (setq spoken (cons beg end))))
                  ((symbol-function
                    'english-reading-mode--start-macos-prefetch-monitor)
                   (lambda () (setq monitor-started t))))
          (english-reading-mode--continuous-warmup-check)
          (should-not spoken)
          (should (= (car scheduled) 0.05))
          (setq ready t)
          (funcall (cadr scheduled))
          (should (equal spoken '(1 . 6)))
          (should monitor-started)
          (should-not (plist-get english-reading-mode--continuous-state
                                 :warmup-texts)))))))

(ert-deftest english-reading-mode-quiet-stop-clears-prefetch-monitor-and-queue ()
  (let ((english-reading-mode--continuous-state '(active))
        (english-reading-mode--continuous-timer nil)
        (english-reading-mode--macos-prefetch-monitor-timer 'monitor)
        cancelled cleared)
    (cl-letf (((symbol-function 'timerp)
               (lambda (object) (eq object 'monitor)))
              ((symbol-function 'cancel-timer)
               (lambda (timer) (setq cancelled timer)))
              ((symbol-function 'kokoro-reader--clear-macos-prefetch)
               (lambda () (setq cleared t))))
      (english-reading-mode-stop-continuous t))
    (should (eq cancelled 'monitor))
    (should cleared)
    (should-not english-reading-mode--macos-prefetch-monitor-timer)))

(ert-deftest kokoro-reader-resident-prefetch-appends-only-missing-suffix ()
  (let* ((current (list :id 0 :key (kokoro-reader--macos-key "現在。")
                        :announced t))
         (kokoro-reader-backend 'macos)
        (kokoro-reader-macos-prefetch-enabled t)
        (kokoro-reader-macos-prefetch-count 3)
        (kokoro-reader--macos-prefetch-queue (list current))
        (kokoro-reader--macos-current-entry nil)
        enqueued)
    (cl-letf (((symbol-function 'kokoro-reader--enqueue-macos-text)
               (lambda (text &optional announced)
                 (let ((entry (list :id (1+ (length enqueued))
                                    :key (kokoro-reader--macos-key text)
                                    :announced announced)))
                   (setq enqueued (append enqueued (list text))
                         kokoro-reader--macos-prefetch-queue
                         (append kokoro-reader--macos-prefetch-queue
                                 (list entry)))
                   entry))))
      (kokoro-reader-prefetch-macos-texts '("一番。" "二番。"))
      (kokoro-reader-prefetch-macos-texts '("一番。" "二番。" "三番。"))
      (should (equal enqueued '("一番。" "二番。" "三番。")))
      (should (= (length kokoro-reader--macos-prefetch-queue) 4)))))

(ert-deftest kokoro-reader-kokoro-prefetch-appends-only-missing-suffix ()
  (let ((kokoro-reader-backend 'kokoro)
        (kokoro-reader-kokoro-prefetch-count 3)
        (kokoro-reader--macos-prefetch-queue nil)
        (kokoro-reader--macos-current-entry nil)
        enqueued)
    (cl-letf (((symbol-function 'kokoro-reader--enqueue-kokoro-text)
               (lambda (text &optional announced)
                 (let ((entry (list :id (1+ (length enqueued))
                                    :backend 'kokoro
                                    :key (kokoro-reader--kokoro-key text)
                                    :announced announced)))
                   (setq enqueued (append enqueued (list text))
                         kokoro-reader--macos-prefetch-queue
                         (append kokoro-reader--macos-prefetch-queue
                                 (list entry)))
                   entry))))
      (kokoro-reader-prefetch-kokoro-texts '("One." "Two."))
      (kokoro-reader-prefetch-kokoro-texts '("One." "Two." "Three."))
      (should (equal enqueued '("One." "Two." "Three.")))
      (should (= (length kokoro-reader--macos-prefetch-queue) 3)))))

(ert-deftest kokoro-reader-kokoro-request-completion-loads-live-entry-by-id ()
  (let* ((audio-file (make-temp-file "kokoro-reader-test-" nil ".wav"))
         (live-entry (list :id 42 :backend 'kokoro :process 'fake-process :audio-file audio-file
                           :volume 0.8 :announced nil))
         (stale-entry (copy-sequence live-entry))
         (kokoro-reader--macos-prefetch-queue (list live-entry))
         (kokoro-reader--kokoro-request-processes '(fake-process))
         wire)
    (unwind-protect
        (progn
          (write-region (make-string 64 ?x) nil audio-file nil 'silent)
          (cl-letf (((symbol-function 'process-exit-status) (lambda (_) 0))
                    ((symbol-function 'kokoro-reader--ensure-macos-bridge)
                     (lambda () 'fake-bridge))
                    ((symbol-function 'process-send-string)
                     (lambda (_process string) (setq wire string)))
                    ((symbol-function 'kokoro-reader--launch-pending-requests)
                     #'ignore))
            (kokoro-reader--kokoro-request-finished
             'fake-process stale-entry nil))
          (let ((command (json-parse-string wire :object-type 'plist)))
            (should (equal (plist-get command :command) "loadFile"))
            (should (= (plist-get command :id) 42))
            (should (equal (plist-get command :path) audio-file))))
      (when (file-exists-p audio-file)
        (delete-file audio-file)))))

(ert-deftest english-reading-mode-prefetches-kokoro-chunks ()
  (with-temp-buffer
    (insert "One. Two. Three.")
    (setq-local sentence-end-double-space nil)
    (setq-local kokoro-reader-backend 'kokoro)
    (let ((source-buffer (current-buffer))
          (english-reading-mode--continuous-state nil)
          (english-reading-mode-macos-prefetch-chunk-count 2)
          queue-limit prefetched)
      (setq english-reading-mode--continuous-state
            (list :buffer source-buffer
                  :window (selected-window)
                  :frame (selected-frame)))
      (cl-letf (((symbol-function 'kokoro-reader-prefetch-kokoro-texts)
                 (lambda (texts)
                   (setq prefetched texts
                         queue-limit kokoro-reader-kokoro-prefetch-count))))
        (english-reading-mode--prefetch-next-macos-sentence
         (list :buffer source-buffer :beg 1 :end 5))
        (should (equal prefetched '("Two." "Three.")))
        (should (= queue-limit 2))))))

(ert-deftest kokoro-reader-resident-enqueue-preserves-buffer-local-settings ()
  (let (wire)
    (with-temp-buffer
      (setq-local kokoro-reader-macos-voice "Kyoko (Enhanced)")
      (setq-local kokoro-reader-macos-rate 600)
      (setq-local kokoro-reader-volume 0.75)
      (let ((kokoro-reader--macos-prefetch-queue nil)
            (kokoro-reader--macos-next-id 0))
        (cl-letf (((symbol-function 'kokoro-reader--ensure-macos-bridge)
                   (lambda () 'fake-bridge))
                  ((symbol-function 'process-send-string)
                   (lambda (_process string) (setq wire string))))
          (kokoro-reader--enqueue-macos-text "速度確認。"))
        (let ((command (json-parse-string wire :object-type 'plist)))
          (should (equal (plist-get command :voice) "Kyoko (Enhanced)"))
          (should (= (plist-get command :rate) 600))
          (should (= (plist-get command :volume) 0.75)))))))

(ert-deftest english-reading-mode-macos-continuous-speaks-two-sentence-chunks ()
  (with-temp-buffer
    (insert "一番目です。二番目です。三番目です。四番目です。五番目です。六番目です。七番目です。")
    (goto-char (point-min))
    (setq-local sentence-end-double-space nil)
    (setq-local kokoro-reader-backend 'macos)
    (let ((english-reading-mode--continuous-state
           (list :buffer (current-buffer)))
          spoken-bounds)
      (cl-letf (((symbol-function 'kokoro-reader--speak-bounds)
                 (lambda (beg end) (setq spoken-bounds (cons beg end)))))
        (english-reading-mode-speak-current-sentence))
      (should (equal (buffer-substring-no-properties
                      (car spoken-bounds) (cdr spoken-bounds))
                     "一番目です。二番目です。")))))

(ert-deftest kokoro-reader-resident-start-announces-prefetched-utterance ()
  (let* ((entry '(:id 7 :key queued :announced nil :started nil))
         (kokoro-reader--macos-prefetch-queue (list entry))
         (kokoro-reader--macos-current-entry nil)
         (kokoro-reader-macos-queued-start-hook nil)
         announced)
    (add-hook 'kokoro-reader-macos-queued-start-hook
              (lambda () (setq announced t)))
    (kokoro-reader--handle-macos-bridge-event
     '(:event "started" :id 7))
    (should announced)
    (should (eq kokoro-reader--macos-current-entry entry))
    (should (plist-get entry :started))))

(ert-deftest english-reading-mode-continuous-resumes-after-completed-chunk ()
  (with-temp-buffer
    (insert "一番目です。二番目です。三番目です。四番目です。")
    (goto-char (point-min))
    (setq-local sentence-end-double-space nil)
    (let ((source-buffer (current-buffer))
          (english-reading-mode--continuous-state nil)
          spoken)
      (setq english-reading-mode--continuous-state
            (list :buffer source-buffer
                  :next-speech-buffer source-buffer
                  :next-speech-position
                  (save-excursion
                    (forward-sentence 3)
                    (point))))
      (cl-letf (((symbol-function 'english-reading-mode-speak-current-sentence)
                 (lambda () (setq spoken (thing-at-point 'sentence t)))))
        (should (english-reading-mode--continuous-resume-next-chunk)))
      (should (string-prefix-p "四番目です。" spoken)))))

(ert-deftest kokoro-reader-resident-finish-removes-entry-and-notifies ()
  (let* ((entry '(:id 8 :key current :announced t :started t))
         (kokoro-reader--macos-prefetch-queue (list entry))
         (kokoro-reader--macos-current-entry entry)
         (kokoro-reader-player-finish-hook nil)
         finished)
    (add-hook 'kokoro-reader-player-finish-hook
              (lambda () (setq finished t)))
    (cl-letf (((symbol-function 'kokoro-reader--delete-overlay) #'ignore))
      (kokoro-reader--handle-macos-bridge-event
       '(:event "finished" :id 8)))
    (should finished)
    (should-not kokoro-reader--macos-current-entry)
    (should-not kokoro-reader--macos-prefetch-queue)))

(ert-deftest kokoro-reader-resident-filter-is-safe-during-reentrant-events ()
  (let ((kokoro-reader--macos-bridge-fragment "")
        events)
    (cl-letf (((symbol-function 'kokoro-reader--handle-macos-bridge-event)
               (lambda (event)
                 (push (plist-get event :id) events)
                 (when (= (plist-get event :id) 1)
                   (kokoro-reader--macos-bridge-filter
                    nil "{\"event\":\"finished\",\"id\":2}\n")))))
      (kokoro-reader--macos-bridge-filter
       nil "{\"event\":\"finished\",\"id\":1}\n")
      (should (equal events '(2 1)))
      (should (string-empty-p kokoro-reader--macos-bridge-fragment)))))

(ert-deftest my-read-k-speech-prefetch-uses-cached-future-pages ()
  (my-read-k-test--isolated
   (let ((my-read-k--last-fingerprint "current")
         (my-read-k--prefetch-source-fingerprint "current")
         (my-read-k--prefetch-queue
          '(((fingerprint . "next")
             (text . "Next page one. Next page two."))
            ((fingerprint . "later")
             (text . "Later page one. Later page two."))))
         (english-reading-mode-macos-continuous-sentence-count 2))
     (should
      (equal (my-read-k--continuous-prefetch-page-texts nil 2)
             '("Next page one. Next page two."
               "Later page one. Later page two."))))))

(ert-deftest my-read-k-continuous-reading-turns-page-with-continuation-intent ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (insert "Last sentence.")
     (goto-char (point-min))
     (setq-local sentence-end-double-space nil)
     (let (requested)
       (cl-letf (((symbol-function 'my-read-k--request-page)
                  (lambda (direction &optional speak)
                    (setq requested (cons direction speak)))))
         (my-read-k-continuous-next)
         (should (equal requested '(next . continuous))))))))

(ert-deftest english-reading-mode-centers-spoken-sentence-start ()
  (save-window-excursion
    (let ((buffer (generate-new-buffer " *english-reading-center-test*"))
          recentered-at
          recentered-line)
      (unwind-protect
          (progn
            (switch-to-buffer buffer)
            (dotimes (number 80)
              (insert (format "Sentence %d.\n" number)))
            (goto-char (point-min))
            (forward-line 60)
            (let ((beg (point))
                  (original-point (1+ (point))))
              (goto-char original-point)
              (cl-letf (((symbol-function 'recenter)
                         (lambda (&optional line)
                           (setq recentered-at (point)
                                 recentered-line line))))
                (english-reading-mode--position-spoken-start
                 (list :window (selected-window)
                       :buffer buffer
                       :beg beg)))
              (should (= recentered-at beg))
              (should-not recentered-line)
              (should (= (point) original-point))))
        (when (buffer-live-p buffer)
          (kill-buffer buffer))))))

(ert-deftest my-read-k-prefetch-starts-immediately-and-only-once-per-source ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (insert (make-string 100 ?x))
     (setq my-read-k--buffer (current-buffer)
           my-read-k--state 'attached
           my-read-k--last-fingerprint "source")
     (goto-char 40)
     (let (sent)
       (cl-letf (((symbol-function 'my-read-k--send)
                  (lambda (command params _callback generation)
                    (setq sent (list command
                                     (my-read-k--alist-get 'prefetchCount params)
                                     generation)))))
         (my-read-k--maybe-prefetch-next)
         (should (equal sent '("prefetchNext" 2 0)))
         (should my-read-k--prefetch-busy-p)
         (my-read-k--maybe-prefetch-next)
         (should (equal sent '("prefetchNext" 2 0))))))))

(ert-deftest my-read-k-prefetch-response-caches-matching-source ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (setq my-read-k--buffer (current-buffer)
           my-read-k--last-fingerprint "source"
           my-read-k--prefetch-busy-p t
           header-line-format " Kindle: attached")
     (my-read-k--finish-prefetch
      '((ok . t)
        (result . ((prefetchSourceFingerprint . "source")
                   (pages . (((fingerprint . "next-1") (text . "Next page 1"))
                             ((fingerprint . "next-2") (text . "Next page 2")))))))
      "source")
     (should (my-read-k--prefetch-valid-p))
     (should (= (length my-read-k--prefetch-queue) 2))
     (should-not my-read-k--prefetch-busy-p)
     (should (string-suffix-p "next ready: 2 | prev ready: 0"
                             header-line-format)))))

(ert-deftest my-read-k-prefetch-response-rejects-stale-source ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (setq my-read-k--buffer (current-buffer)
           my-read-k--last-fingerprint "newer"
           my-read-k--prefetch-busy-p t)
     (my-read-k--finish-prefetch
      '((ok . t)
        (result . ((prefetchSourceFingerprint . "old")
                   (fingerprint . "next") (text . "Old next"))))
      "old")
     (should-not my-read-k--prefetch-queue)
     (should-not my-read-k--prefetch-busy-p))))

(ert-deftest my-read-k-prev-cache-displays-while-forward-prefetch-is-running ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (setq my-read-k--buffer (current-buffer)
           my-read-k--state 'attached
           my-read-k--prefetch-busy-p t
           my-read-k--last-fingerprint "current"
           my-read-k--current-result
           '((fingerprint . "current") (text . "Current page"))
           my-read-k--back-source-fingerprint "current"
           my-read-k--back-queue
           '(((fingerprint . "previous") (text . "Previous page"))))
     (let (sent)
       (cl-letf (((symbol-function 'my-read-k--send)
                  (lambda (command _params _callback _generation)
                    (setq sent command))))
         (my-read-k--request-page 'prev)
         (should (equal (buffer-string) "Previous page\n"))
         (should (equal sent "advancePrev"))
         (should-not my-read-k--pending-intent))))))

(ert-deftest my-read-k-boundary-waits-for-running-prefetch ()
  (my-read-k-test--isolated
   (setq my-read-k--prefetch-busy-p t)
   (my-read-k--request-page 'next t)
   (should (equal my-read-k--pending-intent '(next . t)))
   (should-not my-read-k--busy-p)))

(ert-deftest my-read-markdown-continuous-crosses-atx-headings ()
  (require 'markdown-mode)
  (with-temp-buffer
    (markdown-mode)
    (insert "前の文です。\n\n### ### 第2巻 — カトリック哲学\n\n次の本文です。\n")
    (goto-char (point-min))
    (let ((kokoro-reader-backend 'kokoro)
          (english-reading-mode--continuous-state nil)
          spoken)
      (cl-letf (((symbol-function 'kokoro-reader--speak-bounds)
                 (lambda (beg end)
                   (push (buffer-substring-no-properties beg end) spoken))))
        (english-reading-mode--continuous-default-next)
        (should (equal (car spoken) "### ### 第2巻 — カトリック哲学"))
        (english-reading-mode--continuous-default-next)
        (should (equal (car spoken) "次の本文です。"))
        (should-error (english-reading-mode--continuous-default-next)
                      :type 'user-error)
        ;; Chunk continuation lands directly on the heading after playback.
        (goto-char (point-min))
        (forward-line 2)
        (setq english-reading-mode--continuous-state
              (list :buffer (current-buffer)
                    :next-speech-buffer (current-buffer)
                    :next-speech-position (point)))
        (should (english-reading-mode--continuous-resume-next-chunk))
        (should (equal (car spoken) "### ### 第2巻 — カトリック哲学"))
        ;; macOS chunking must also cross the heading while preparing audio.
        (goto-char (point-min))
        (let* ((kokoro-reader-backend 'macos)
               (english-reading-mode-macos-continuous-sentence-count 3)
               (bounds (english-reading-mode--sentence-bounds))
               (chunk (english-reading-mode--macos-continuous-bounds
                       (car bounds) (cdr bounds))))
          (should (string-suffix-p "次の本文です。"
                                   (buffer-substring-no-properties
                                    (car chunk) (cdr chunk)))))))))

(ert-deftest my-read-restart-speech-kills-old-engine-before-stop-and-start ()
  (let ((kokoro-reader--macos-bridge-process 'old)
        (kokoro-reader--macos-bridge-ready-p t)
        (kokoro-reader--macos-bridge-fragment "stale")
        calls)
    (cl-letf (((symbol-function 'process-live-p) (lambda (p) (eq p 'old)))
              ((symbol-function 'delete-process)
               (lambda (p)
                 (should (eq p 'old))
                 (should-not kokoro-reader--macos-bridge-process)
                 (push 'delete calls)))
              ((symbol-function 'english-reading-mode-stop-continuous)
               (lambda () (push 'stop calls)))
              ((symbol-function 'kokoro-reader--ensure-macos-bridge)
               (lambda ()
                 (should-not kokoro-reader--macos-bridge-ready-p)
                 (should (equal kokoro-reader--macos-bridge-fragment ""))
                 (push 'start calls))))
      (my-read-restart-japanese-speech)
      (should (equal (nreverse calls) '(delete stop start))))))

(ert-deftest my-read-manual-japanese-eww-speech-survives-render-and-resets ()
  (with-temp-buffer
    (eww-mode)
    (let ((inhibit-read-only t)) (insert "English navigation. README content."))
    (let ((kokoro-reader-backend 'kokoro)
          stopped)
      (cl-letf (((symbol-function 'my/read--center-window-active-p) (lambda () t))
                ((symbol-function 'english-reading-mode-stop-continuous)
                 (lambda () (setq stopped t))))
        (my-read-use-japanese-speech)
        (should stopped)
        (should (eq my/read-speech-language-override 'ja))
        (should (eq kokoro-reader-backend 'macos))
        (should (equal my/read-source-language "ja"))
        (should (equal kokoro-reader-macos-voice my/read-japanese-macos-voice))
        (run-hooks 'eww-after-render-hook)
        (should (eq kokoro-reader-backend 'macos))
        (my-read-use-auto-speech)
        (should-not my/read-speech-language-override)
        (should (equal my/read-source-language "en"))
        (should-not (local-variable-p 'kokoro-reader-backend))
        (let ((inhibit-read-only t)) (insert "日本語のREADME。"))
        (my-read-use-auto-speech)
        (should (eq kokoro-reader-backend 'macos))
        (my-read-set-speech-language 'en)
        (should (eq kokoro-reader-backend 'kokoro))
        (should (equal my/read-source-language "en"))))))

(ert-deftest my-read-k-manual-speech-language-survives-pages-and-resets ()
  (my-read-k-test--isolated
   (with-temp-buffer
     (my-read-k-document-mode)
     (setq my-read-k--buffer (current-buffer))
     (let ((kokoro-reader-backend 'kokoro)
           (stops 0))
       (cl-letf (((symbol-function 'my/read--center-window-active-p) (lambda () t))
                 ((symbol-function 'english-reading-mode-stop-continuous)
                  (lambda () (cl-incf stops))))
         (my-read-k--apply-page
          '((text . "First page.") (language . "en") (fingerprint . "1")) nil nil)
         (my-read-use-japanese-speech)
         (should (= stops 1))
         (should (eq kokoro-reader-backend 'macos))
         (should (equal kokoro-reader-macos-voice my/read-japanese-macos-voice))
         (should (= kokoro-reader-macos-rate my/read-japanese-macos-rate))
         (should (string-match-p "JA/macOS" header-line-format))
         (my-read-k--apply-page
          '((text . "Next page.") (language . "en") (fingerprint . "2")) 'next nil)
         (should (eq my/read-speech-language-override 'ja))
         (should (equal my/read-source-language "ja"))
         (should (eq kokoro-reader-backend 'macos))
         (my-read-use-auto-speech)
         (should (equal my/read-source-language "en"))
         (should-not (local-variable-p 'kokoro-reader-backend))
         (should (= kokoro-reader-macos-rate my/read-english-macos-rate))
         (my-read-k--apply-page
          '((text . "日本語のページ。") (language . "ja") (fingerprint . "3")) 'next nil)
         (should (eq kokoro-reader-backend 'macos))
         (my-read-set-speech-language 'en)
         (should (equal my/read-source-language "en"))
         (should (string-match-p "EN/Kokoro" header-line-format))
         (my-read-k--apply-page
          '((text . "次のページ。") (language . "ja") (fingerprint . "4")) 'next nil)
         (should (eq kokoro-reader-backend 'kokoro))
         (should (equal my/read-source-language "en"))
         (my-read-use-auto-speech)
         (should (equal my/read-source-language "ja"))
         (should (eq kokoro-reader-backend 'macos)))))))

(ert-deftest my-read-k-speech-language-requires-active-center ()
  (with-temp-buffer
    (my-read-k-document-mode)
    (cl-letf (((symbol-function 'my/read--center-window-active-p) (lambda () nil)))
      (should-error (my-read-set-speech-language 'ja) :type 'user-error)
      (should-not my/read-speech-language-override))))

(provide 'reader-speech-tests)

(ert-deftest my-read-change-speed-selects-current-language ()
  (dolist (language '("en" "ja"))
    (with-temp-buffer
      (setq-local my/read-source-language language)
      (let ((my/read-japanese-speech-backend 'macos)
            (kokoro-reader-backend 'kokoro)
            changed)
        (cl-letf (((symbol-function 'read-number) (lambda (&rest _) (if (equal language "en") 1.2 400)))
                  ((symbol-function 'my/read--change-language-speed)
                   (lambda (lang rate &optional backend) (setq changed (list lang rate backend)))))
          (call-interactively #'my-read-change-speed)
          (should (equal changed (if (equal language "en") '("en" 1.2 t) '("ja" 400 nil)))))))))

(ert-deftest my-read-change-speed-is-only-interactive-speed-command ()
  (should (commandp 'my-read-change-speed))
  (should-not (commandp 'my-read-change-english-speed))
  (should-not (commandp 'my-read-change-japanese-speed)))
