;;; reader-http-speech-tests.el --- HTTP speech tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'reader-http-speech)
(require 'reader-http-speech-transport)

(ert-deftest reader-http-transport-preserves-current-language-and-speed ()
  (let ((kokoro-reader-backend 'macos)
        (kokoro-reader-macos-voice "Kyoko (Enhanced)")
        (kokoro-reader-macos-rate 300)
        (kokoro-reader-lang-code "b"))
    (let ((payload (json-read-from-string (reader-http-speech-transport--payload "日本語です。"))))
      (should (equal (alist-get 'language payload) "ja"))
      (should (equal (alist-get 'voice payload) "Kyoko"))
      (should (= (alist-get 'rate payload) 300))
      (should (= (alist-get 'speed payload) 1.0)))))

(ert-deftest reader-http-transport-reserves-file-instead-of-local-synthesis ()
  (let ((reader-http-speech-transport-mode t)
        (kokoro-reader-backend 'macos)
        (kokoro-reader-macos-voice "Kyoko")
        (kokoro-reader-macos-rate 250)
        (kokoro-reader--macos-prefetch-queue nil)
        (kokoro-reader--kokoro-pending-entries nil)
        (kokoro-reader--kokoro-api-ready-p nil)
        (kokoro-reader--macos-next-id 0)
        sent launched entry)
    (unwind-protect
        (cl-letf (((symbol-function 'kokoro-reader--ensure-macos-bridge) (lambda () 'bridge))
                  ((symbol-function 'process-send-string) (lambda (_p text) (setq sent text)))
                  ((symbol-function 'kokoro-reader--launch-pending-requests) (lambda () (setq launched t))))
          (setq entry (reader-http-speech-transport--enqueue (lambda (&rest _) (error "Local synthesis called")) "日本語です。" t))
          (should (string-match-p "reserve" sent))
          (should launched)
          (should (equal (plist-get entry :endpoint) reader-http-speech-endpoint))
          (should (plist-get entry :http-payload))
          (should (eq entry (car kokoro-reader--kokoro-pending-entries))))
      (when entry (delete-file (plist-get entry :audio-file))))))

(ert-deftest reader-http-speech-language-parameters ()
  (let ((reader-http-speech-japanese-speed 1.5)
        (reader-http-speech-english-speed 0.8))
    (should (equal (alist-get 'backend (reader-http-speech--request "日本語" "ja")) "macos"))
    (should (= (alist-get 'speed (reader-http-speech--request "English" "en")) 0.8))
    (should (= (alist-get 'speed (reader-http-speech--request "日本語" "ja")) 1.5))))

(ert-deftest reader-http-speech-invalid-text-is-rejected ()
  (should-error (reader-http-speech--request "  " "ja") :type 'user-error)
  (should-error (reader-http-speech--request "text" "xx") :type 'user-error)
  (should-error (reader-http-speech--request (make-string 24001 ?a) "en") :type 'user-error))

(ert-deftest reader-http-speech-only-sends-selected-region ()
  (with-temp-buffer
    (insert "before selected after")
    (goto-char 8)
    (set-mark 16)
    (let ((transient-mark-mode t) (mark-active t) sent)
      (cl-letf (((symbol-function 'reader-http-speech-speak)
                 (lambda (text language) (setq sent (list text language)))))
        (reader-http-speech-read-japanese))
      (should (equal sent '("selected" "ja"))))))
